var months={all:"Tutto l'anno","01":"Gennaio","02":"Febbraio","03":"Marzo","04":"Aprile","05":"Maggio","06":"Giugno","07":"Luglio","08":"Agosto","09":"Settembre","10":"Ottobre","11":"Novembre","12":"Dicembre"};
var schedule={},changes=JSON.parse(localStorage.getItem("turnistica-changes")||"[]"),roles=JSON.parse(localStorage.getItem("turnistica-roles")||"{}"),page="original",person=sessionStorage.getItem("turnistica-user")||"",month="01",wheelDate="";
var app=document.querySelector("#app"),title=document.querySelector("#pageTitle");
var passwordHash="e533798c550dce5b8ab4dbe2b0ca7408d842c4b41494b09cd2b587a40583da90";

fetch("schedule-compact.json").then(function(r){return r.json()}).then(function(d){Object.keys(d.codes).forEach(function(p){schedule[p]={};Object.keys(d.codes[p]).forEach(function(m){schedule[p][m]=d.codes[p][m].map(function(code,i){return{date:d.months[m][i].date,day:d.months[m][i].day,code:code}})})});if(!person)person=Object.keys(schedule).indexOf("GRAN")>=0?"GRAN":Object.keys(schedule)[0];wheelDate=defaultDate();render()});
document.querySelectorAll("nav button").forEach(function(b){b.onclick=function(){page=b.dataset.page;document.querySelectorAll("nav button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");title.textContent=page==="original"?"Turnistica originale":page==="changes"?"Variazioni di turno":"Turnistica aggiornata";render()}});
function people(){return Object.keys(schedule).sort()}
function users(){return people().concat(["PAPA"]).filter(function(p,i,a){return a.indexOf(p)===i}).sort()}
function roleOf(p){return p==="PAPA"?"capo-pilota":roles[p]==="sottocapo"?"sottocapo":"lettura"}
function canWrite(){return roleOf(person)==="capo-pilota"||roleOf(person)==="sottocapo"}
function canManage(){return person==="PAPA"}
function allEntries(p){return Object.values(schedule[p]||{}).flat()}
function dates(){return allEntries(people()[0]).map(function(e){return e.date})}
function defaultDate(){var now=new Date(),d=String(now.getDate()).padStart(2,"0"),m=String(now.getMonth()+1).padStart(2,"0"),v=d+"/"+m+"/26";return dates().indexOf(v)>=0?v:dates()[0]||"01/01/26"}
function raw(p,date){return allEntries(p).find(function(e){return e.date===date})}
function isOff(code){return !code||code.charAt(0)==="F"}
function effective(p,date){var e=raw(p,date);if(!e||isOff(e.code))return e?e.code:"-";var ds=dates(),i=ds.indexOf(date),k=i,streak=[];while(k>=0){var prev=raw(p,ds[k]);if(!prev||isOff(prev.code))break;streak.unshift(prev);k--}var start=streak[0]&&streak[0].code,offset=streak.length-1;if(offset===4&&start==="R1")return"11";if(offset===4&&start==="R2")return"22";if(e.code==="G")return"11";return e.code}
function shiftedDate(date,delta){var ds=dates(),i=ds.indexOf(date);return i>=0&&ds[i+delta]?ds[i+delta]:null}
function assignedCode(p,date){if(!date)return null;var e=raw(p,date),code=e&&!isOff(e.code)?effective(p,date):null;changes.filter(function(c){return c.date===date&&(c.status==="approved"||c.status==="pending")}).forEach(function(c){if(c.person===p)code=null;if(c.substitute===p)code=c.code||effective(c.person,date)});return code}
function guardConflict(p,date,code){if(assignedCode(p,shiftedDate(date,-1))==="11")return"Il pilota ha effettuato una guardia 11 il giorno precedente e non può iniziare un nuovo turno alle 06:00.";if(code==="11"&&assignedCode(p,shiftedDate(date,1)))return"Il turno 11 termina alle 08:00 del giorno successivo: il pilota non può lavorare anche il giorno seguente.";return""}
function entries(){return month==="all"?allEntries(person):(schedule[person]&&schedule[person][month]||[])}
function selectField(label,value,options,action){var s="<label class='field'>"+label+"<select data-action='"+action+"'>";options.forEach(function(o){s+="<option value='"+o[0]+"' "+(o[0]===value?"selected":"")+">"+o[1]+"</option>"});return s+"</select></label>"}
function toolbar(){return "<div class='toolbar'>"+selectField("Persona",person,people().map(function(p){return[p,p]}),"person")+selectField("Mese",month,Object.entries(months).filter(function(o){return o[0]!=="all"}),"month")+"</div>"}
function tag(c){return "<span class='tag "+String(c).toLowerCase().replace(/[^a-z0-9]/g,"")+"'>"+c+"</span>"}
function approvedFor(date){return changes.filter(function(c){return c.date===date&&c.status==="approved"&&c.substitute})}
function wheel(){var list=people().map(function(p){var e=raw(p,wheelDate);return e&&!isOff(e.code)?{person:p,code:effective(p,wheelDate),original:p}:null}).filter(Boolean);approvedFor(wheelDate).forEach(function(c){var x=list.find(function(e){return e.original===c.person});if(x){x.replaced=true;x.replacedBy=c.substitute;x.person=c.substitute}});var order={R1:1,R2:2,R:3,"11":4,"22":5};return list.sort(function(a,b){return(order[a.code]||9)-(order[b.code]||9)||a.person.localeCompare(b.person)})}
function dateInput(){var parts=wheelDate.split("/"),iso=parts.length===3?"20"+parts[2]+"-"+parts[1]+"-"+parts[0]:"";return "<label class='field'>Giorno della ruota<input id='wheelDate' type='date' value='"+iso+"'></label>"}
function wheelPanel(){var list=wheel();var h="<section class='wheel-panel'><div class='wheel-head'><div><small>RUOTA DEL GIORNO</small><h3>"+wheelDate+"</h3><p>10 piloti presenti · turni originali con sostituzioni applicate</p></div>"+dateInput()+"</div><div class='wheel-grid'>";list.forEach(function(e){h+="<div class='wheel-card "+(e.original===person?"mine ":"")+(e.replaced?"replacement":"")+"\">"+tag(e.code)+"<b>"+e.person+"</b>"+(e.replaced?"<small>sostituisce "+e.original+"</small>":"")+"</div>"});if(!list.length)h+="<div class='empty'>Nessun pilota in servizio per questa data.</div>";return h+="</div><div class='wheel-legend'><span>R1 montante</span><span>R2 montante</span><span>11 guardia notturna</span><span>22 smontante alle 22</span><span>R ruota</span></div></section>"}
function table(items,updated){var h="<div class='table'><table><thead><tr><th>Data</th><th>Giorno</th><th>Turno</th><th>Stato</th></tr></thead><tbody>";items.forEach(function(e){var code=effective(person,e.date),c=changes.find(function(x){return x.person===person&&x.date===e.date&&x.status==="approved"});h+="<tr class='"+(c?"changed":"")+(e.date===wheelDate?" today-row":"")+"'><td>"+e.date+"</td><td>"+e.day+"</td><td>"+tag(code)+"</td><td>"+(c?"<span class='changed-label'>Sostituito da "+c.substitute+"</span>":"<span class='muted'>"+(updated?"Originale":"Da prospetto")+"</span>")+"</td></tr>"});return h+"</tbody></table></div>"}
function render(){if(!Object.keys(schedule).length){app.innerHTML="<div class='empty'>Caricamento turnistica...</div>";return}if(!sessionStorage.getItem("turnistica-user")){login();return}document.querySelector("#userBadge").textContent=person.slice(0,2);if(page==="original")original();else if(page==="changes")(canWrite()?changePage:readonlyChanges)();else updated();wire()}
function login(){document.querySelector(".sidebar").style.display="none";document.querySelector("header").style.display="none";app.innerHTML="<div class='login-shell'><div class='login-card'><div class='mark'>T</div><p class='login-kicker'>ACCESSO TURNISTICA</p><h2>Benvenuto</h2><p>Inserisci il tuo cognome abbreviato e la password comune per consultare i turni.</p><label class='field'>Cognome<select id='loginPerson'><option value=''>Seleziona il tuo cognome</option>"+users().map(function(p){return"<option>"+p+"</option>"}).join("")+"</select></label><label class='field'>Password<input id='loginPassword' type='password' autocomplete='current-password'></label><button class='button' id='loginButton'>Accedi</button><div id='loginError' class='login-error'></div><small class='login-foot'>Accesso personale alla turnistica 2026</small></div></div>";document.querySelector("#loginButton").onclick=checkLogin}
async function checkLogin(){var p=document.querySelector("#loginPerson").value,pw=document.querySelector("#loginPassword").value,digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(pw)),hash=Array.from(new Uint8Array(digest)).map(function(b){return b.toString(16).padStart(2,"0")}).join("");if(!p||hash!==passwordHash){document.querySelector("#loginError").textContent="Cognome o password non validi.";return}person=p;sessionStorage.setItem("turnistica-user",p);document.querySelector(".sidebar").style.display="flex";document.querySelector("header").style.display="flex";render()}
function logout(){sessionStorage.removeItem("turnistica-user");person="";page="original";document.querySelectorAll("nav button").forEach(function(x){x.classList.toggle("active",x.dataset.page==="original")});document.querySelector("#pageTitle").textContent="Turnistica originale";login()}
function managementPanel(){if(!canManage())return"";var h="<section class='management'><div class='section'><div><h3>Gestione autorizzazioni</h3><p class='muted'>PAPA è Capo pilota. Può autorizzare al massimo due Sottocapi alla scrittura.</p></div><span class='status approved'>Capo pilota: PAPA</span></div><div class='management-grid'>";people().forEach(function(p){var r=roleOf(p);h+="<label class='role-row'><b>"+p+"</b><select data-role='"+p+"'><option value='lettura' "+(r==="lettura"?"selected":"")+">Solo lettura</option><option value='sottocapo' "+(r==="sottocapo"?"selected":"")+">Sottocapo</option></select></label>"});return h+"</div><small class='muted'>Sottocapi autorizzati: "+people().filter(function(p){return roleOf(p)==="sottocapo"}).length+" / 2</small></section>"}
function original(){app.innerHTML="<div class='content'><div class='intro'><div><h3>La ruota del giorno</h3><p>Ogni pilota lavora 5 giorni e riposa 4. La ruota mostra i 10 piloti in servizio, con R1, R2, 11, 22 e le ruote R.</p></div><div class='metric'><strong>"+people().length+"</strong><small>piloti</small></div><div class='metric'><strong>10</strong><small>in servizio</small></div></div>"+wheelPanel()+toolbar()+table(entries())+managementPanel()+"</div>"}
function readonlyChanges(){app.innerHTML="<div class='content'><div class='intro'><div><h3>Variazioni di turno</h3><p>Questa sezione è consultabile in sola lettura. Solo il Capo pilota e i Sottocapi autorizzati possono inserire o applicare variazioni.</p></div></div>"+wheelPanel()+"<div class='rules'><b>Accesso in sola lettura</b><span>Le variazioni vengono gestite dal Capo pilota e dai Sottocapi.</span></div></div>"}
function changePage(){var pending=changes.filter(function(c){return c.status==="pending"}).length,approved=changes.filter(function(c){return c.status==="approved"}).length;var h="<div class='content'><div class='intro'><div><h3>Inserisci una sostituzione</h3><p>Indica chi non lavora e chi lo sostituisce. Il codice del turno resta quello del pilota originale.</p></div><div class='metric'><strong>"+pending+"</strong><small>da approvare</small></div><div class='metric'><strong>"+approved+"</strong><small>applicate</small></div></div>"+wheelPanel()+"<div class='form'><label class='field'>Pilota assente<select id='fperson'>"+people().map(function(p){return"<option>"+p+"</option>"}).join("")+"</select></label><label class='field'>Data<input id='fdate' placeholder='gg/mm/26' value='"+wheelDate+"'></label><label class='field'>Sostituito da<select id='fsubstitute'>"+people().map(function(p){return"<option>"+p+"</option>"}).join("")+"</select></label><label class='field'>Nota predefinita<select id='fpreset'><option value=''>Nessuna nota predefinita</option><option>Cambio turno volontario</option><option>PM</option><option>Cambio ruota</option></select></label><label class='field wide'>Nota libera<input id='fnote' placeholder='Aggiungi una nota facoltativa'></label><button class='button' id='add'>Aggiungi</button></div><div class='section'><h3>Registro variazioni</h3><span class='muted'>"+changes.length+" registrate</span></div><div class='cards'>";if(!changes.length)h+="<div class='empty'>Nessuna variazione inserita.</div>";changes.forEach(function(c){h+="<div class='card'><div><b>"+c.date+"</b><small>"+c.person+" → "+(c.substitute||"-")+"</small></div><div class='arrow'>"+tag(c.code||c.from||"R")+"</div><div class='note muted'>"+(c.note||"Nessuna nota")+"</div><span class='status "+(c.status==="approved"?"approved":"pending")+"'>"+(c.status==="approved"?"Applicata":"In attesa")+"</span><div><button data-apply='"+c.id+"'>"+(c.status==="pending"?"Applica ":"")+"</button><button data-remove='"+c.id+"'>Rimuovi</button></div></div>"});h+="</div><div class='rules'><b>Regole</b><span>• 5 giorni di lavoro / 4 di riposo</span><span>• R1 al quinto giorno diventa 11</span><span>• R2 al quinto giorno diventa 22</span><span>• il turno originale resta invariato</span></div></div>";app.innerHTML=h}
function updated(){var approved=changes.filter(function(c){return c.status==="approved"}).length;app.innerHTML="<div class='content'><div class='intro'><div><h3>Ruota aggiornata</h3><p>Le sostituzioni approvate cambiano il pilota presente, ma non il turno assegnato.</p></div><div class='metric'><strong>"+approved+"</strong><small>modifiche attive</small></div></div>"+wheelPanel()+toolbar()+table(entries(),true)+"</div>"}
function save(){localStorage.setItem("turnistica-changes",JSON.stringify(changes))}
function saveRoles(){localStorage.setItem("turnistica-roles",JSON.stringify(roles))}
function wire(){document.querySelectorAll("[data-action]").forEach(function(x){x.onchange=function(){if(x.dataset.action==="person")person=x.value;else month=x.value;render()}});document.querySelectorAll("[data-role]").forEach(function(x){x.onchange=function(){var count=people().filter(function(p){return roleOf(p)==="sottocapo"}).length;if(x.value==="sottocapo"&&roleOf(x.dataset.role)!=="sottocapo"&&count>=2){alert("Sono già presenti due Sottocapi.");render();return}if(x.value==="sottocapo")roles[x.dataset.role]="sottocapo";else delete roles[x.dataset.role];saveRoles();render()}});var wd=document.querySelector("#wheelDate");if(wd)wd.onchange=function(){var p=wd.value.split("-");wheelDate=p[2]+"/"+p[1]+"/"+p[0].slice(2);render()};var add=document.querySelector("#add");if(add)add.onclick=function(){var p=document.querySelector("#fperson").value,d=document.querySelector("#fdate").value.toUpperCase(),sub=document.querySelector("#fsubstitute").value,e=raw(p,d),se=raw(sub,d),preset=document.querySelector("#fpreset").value,free=document.querySelector("#fnote").value.trim(),note=[preset,free].filter(Boolean).join(" — ");if(!/^\d{2}\/\d{2}\/26$/.test(d)||!e||isOff(e.code)||p===sub){alert("Inserisci una data lavorativa valida e un sostituto diverso.");return}if(se&&!isOff(se.code)){alert("Il sostituto risulta già in servizio quel giorno.");return}changes.push({id:Date.now().toString(),person:p,date:d,substitute:sub,code:effective(p,d),from:effective(p,d),note:note,status:"pending"});save();wheelDate=d;render()};document.querySelectorAll("[data-apply]").forEach(function(x){x.onclick=function(){var c=changes.find(function(c){return c.id===x.dataset.apply});if(c)c.status="approved";save();render()}});document.querySelectorAll("[data-remove]").forEach(function(x){x.onclick=function(){changes=changes.filter(function(c){return c.id!==x.dataset.remove});save();render()}})}
document.addEventListener("click",function(ev){if(!ev.target||ev.target.id!=="add")return;var p=document.querySelector("#fperson").value,d=document.querySelector("#fdate").value.toUpperCase(),sub=document.querySelector("#fsubstitute").value,e=raw(p,d),code=e?effective(p,d):"",se=assignedCode(sub,d),reason=guardConflict(sub,d,code);if(!/^\d{2}\/\d{2}\/26$/.test(d)||!e||isOff(e.code)||p===sub||se||reason){ev.preventDefault();ev.stopImmediatePropagation();alert(se?"Il sostituto risulta già impegnato quel giorno.":reason||"Inserisci una data lavorativa valida e un sostituto diverso.");}},true)
document.addEventListener("click",function(ev){if(ev.target&&ev.target.id==="logout")logout()})
