var months={all:"Tutto l'anno","01":"Gennaio","02":"Febbraio","03":"Marzo","04":"Aprile","05":"Maggio","06":"Giugno","07":"Luglio","08":"Agosto","09":"Settembre","10":"Ottobre","11":"Novembre","12":"Dicembre"};
var schedule={},changes=JSON.parse(localStorage.getItem("turnistica-changes")||"[]"),page="original",person=sessionStorage.getItem("turnistica-user")||"",month="01";
var app=document.querySelector("#app"),title=document.querySelector("#pageTitle");
var passwordHash="e533798c550dce5b8ab4dbe2b0ca7408d842c4b41494b09cd2b587a40583da90";
fetch("schedule-compact.json").then(function(r){return r.json()}).then(function(d){Object.keys(d.codes).forEach(function(p){schedule[p]={};Object.keys(d.codes[p]).forEach(function(m){schedule[p][m]=d.codes[p][m].map(function(code,i){return{date:d.months[m][i].date,day:d.months[m][i].day,code:code}})})});if(!person)person=Object.keys(schedule).indexOf("GRAN")>=0?"GRAN":Object.keys(schedule)[0];render()});
document.querySelectorAll("nav button").forEach(function(b){b.onclick=function(){page=b.dataset.page;document.querySelectorAll("nav button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");title.textContent=page==="original"?"Turnistica originale":page==="changes"?"Variazioni di turno":"Turnistica aggiornata";render()}});
function people(){return Object.keys(schedule).sort()}
function entries(){return month==="all"?Object.values(schedule[person]||{}).flat():(schedule[person]&&schedule[person][month]||[])}
function selectField(label,value,options,action){var s="<label class='field'>"+label+"<select data-action='"+action+"'>";options.forEach(function(o){s+="<option value='"+o[0]+"' "+(o[0]===value?"selected":"")+">"+o[1]+"</option>"});return s+"</select></label>"}
function toolbar(){return "<div class='toolbar'>"+selectField("Persona",person,people().map(function(p){return[p,p]}),"person")+selectField("Mese",month,Object.entries(months),"month")+"</div>"}
function tag(c){return "<span class='tag "+c.toLowerCase()+"'>"+c+"</span>"}
function table(items,updated){var h="<div class='table'><table><thead><tr><th>Data</th><th>Giorno</th><th>Turno</th><th>Stato</th></tr></thead><tbody>";items.forEach(function(e){var c=changes.find(function(x){return x.person===person&&x.date===e.date&&x.status==="approved"});var code=c?c.to:e.code;h+="<tr class='"+(c?"changed":"")+"'><td>"+e.date+"</td><td>"+e.day+"</td><td>"+tag(code)+"</td><td>"+(c?"<span class='changed-label'>Variazione applicata</span>":"<span class='muted'>"+(updated?"Originale":"Da prospetto")+"</span>")+"</td></tr>"});return h+"</tbody></table></div>"}
function render(){if(!Object.keys(schedule).length){app.innerHTML="<div class='empty'>Caricamento turnistica...</div>";return}if(!sessionStorage.getItem("turnistica-user")){login();return}document.querySelector("#userBadge").textContent=person.slice(0,2);if(page==="original")original();else if(page==="changes")changePage();else updated();wire()}
function login(){document.querySelector(".sidebar").style.display="none";document.querySelector("header").style.display="none";app.innerHTML="<div class='login-shell'><div class='login-card'><div class='mark'>T</div><p class='login-kicker'>ACCESSO TURNISTICA</p><h2>Benvenuto</h2><p>Inserisci il tuo cognome abbreviato e la password comune per consultare i turni.</p><label class='field'>Cognome<select id='loginPerson'><option value=''>Seleziona il tuo cognome</option>"+people().map(function(p){return"<option>"+p+"</option>"}).join("")+"</select></label><label class='field'>Password<input id='loginPassword' type='password' autocomplete='current-password'></label><button class='button' id='loginButton'>Accedi</button><div id='loginError' class='login-error'></div><small class='login-foot'>Accesso personale alla turnistica 2026</small></div></div>";document.querySelector("#loginButton").onclick=checkLogin}
async function checkLogin(){var p=document.querySelector("#loginPerson").value,pw=document.querySelector("#loginPassword").value;var digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(pw)),hash=Array.from(new Uint8Array(digest)).map(function(b){return b.toString(16).padStart(2,"0")}).join("");if(!p||hash!==passwordHash){document.querySelector("#loginError").textContent="Cognome o password non validi.";return}person=p;sessionStorage.setItem("turnistica-user",p);document.querySelector(".sidebar").style.display="flex";document.querySelector("header").style.display="flex";render()}
function original(){app.innerHTML="<div class='content'><div class='intro'><div><h3>Il prospetto di base</h3><p>Turnistica originale completa, senza le tavole di marea. Seleziona persona e mese per consultare i turni.</p></div><div class='metric'><strong>"+people().length+"</strong><small>persone</small></div><div class='metric'><strong>12</strong><small>mesi</small></div></div>"+toolbar()+table(entries())+"</div>"}
function changePage(){var pending=changes.filter(function(c){return c.status==="pending"}).length,approved=changes.filter(function(c){return c.status==="approved"}).length;var h="<div class='content'><div class='intro'><div><h3>Automatizza i cambi turno</h3><p>Inserisci una variazione: il programma recupera il turno originale e prepara la modifica senza annotazioni manuali.</p></div><div class='metric'><strong>"+pending+"</strong><small>da approvare</small></div><div class='metric'><strong>"+approved+"</strong><small>applicate</small></div></div><div class='form'><label class='field'>Persona<select id='fperson'>";people().forEach(function(p){h+="<option>"+p+"</option>"});h+="</select></label><label class='field'>Data<input id='fdate' placeholder='gg/mm/26'></label><label class='field'>Nuovo turno<input id='fcode' placeholder='R1, R2, G...'></label><label class='field wide'>Nota<input id='fnote' placeholder='Motivo o annotazione facoltativa'></label><button class='button' id='add'>Aggiungi</button></div><div class='section'><h3>Registro variazioni</h3><span class='muted'>"+changes.length+" registrate</span></div><div class='cards'>";if(!changes.length)h+="<div class='empty'>Nessuna variazione inserita.</div>";changes.forEach(function(c){h+="<div class='card'><div><b>"+c.date+"</b><small>"+c.person+"</small></div><div class='arrow'>"+tag(c.from)+" → "+tag(c.to)+"</div><div class='note muted'>"+(c.note||"Nessuna nota")+"</div><span class='status "+(c.status==="approved"?"approved":"pending")+"'>"+(c.status==="approved"?"Applicata":"In attesa")+"</span><div><button data-apply='"+c.id+"'>"+(c.status==="pending"?"Applica ":"")+"</button><button data-remove='"+c.id+"'>Rimuovi</button></div></div>"});h+="</div><div class='rules'><b>Controlli automatici previsti</b><span>• ciclo 5 giorni lavoro / 4 riposo</span><span>• circa 24 giorni ferie ogni 3 mesi</span><span>• conflitti evidenziati prima dell'approvazione</span></div></div>";app.innerHTML=h}
function updated(){var approved=changes.filter(function(c){return c.status==="approved"}).length;app.innerHTML="<div class='content'><div class='intro'><div><h3>Turnistica aggiornata</h3><p>Le variazioni approvate vengono applicate automaticamente al prospetto originale e restano evidenziate.</p></div><div class='metric'><strong>"+approved+"</strong><small>modifiche attive</small></div></div>"+toolbar()+table(entries(),true)+"</div>"}
function save(){localStorage.setItem("turnistica-changes",JSON.stringify(changes))}
function wire(){document.querySelectorAll("[data-action]").forEach(function(x){x.onchange=function(){if(x.dataset.action==="person")person=x.value;else month=x.value;render()}});var add=document.querySelector("#add");if(add)add.onclick=function(){var p=document.querySelector("#fperson").value,d=document.querySelector("#fdate").value.toUpperCase(),to=document.querySelector("#fcode").value.toUpperCase(),original=((schedule[p]&&schedule[p][d.slice(3,5)])||[]).find(function(e){return e.date===d});if(/^\d{2}\/\d{2}\/26$/.test(d)===false||!to){alert("Inserisci data gg/mm/26 e nuovo turno.");return}changes.push({id:Date.now().toString(),person:p,date:d,from:original?original.code:"-",to:to,note:document.querySelector("#fnote").value,status:"pending"});save();render()};document.querySelectorAll("[data-apply]").forEach(function(x){x.onclick=function(){var c=changes.find(function(c){return c.id===x.dataset.apply});if(c)c.status="approved";save();render()}});document.querySelectorAll("[data-remove]").forEach(function(x){x.onclick=function(){changes=changes.filter(function(c){return c.id!==x.dataset.remove});save();render()}})}
