var suggestions=JSON.parse(localStorage.getItem("turnistica-suggestions")||"[]");
var monthOptions=[["01","Gennaio"],["02","Febbraio"],["03","Marzo"],["04","Aprile"],["05","Maggio"],["06","Giugno"],["07","Luglio"],["08","Agosto"],["09","Settembre"],["10","Ottobre"],["11","Novembre"],["12","Dicembre"]];

function escapeHtml(value){return String(value==null?"":value).replace(/[&<>"']/g,function(ch){return{"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]})}
function isGranara(){return person==="GRAN"}
function canSuggest(){return roleOf(person)==="sottocapo"}
function suggestionsSave(){localStorage.setItem("turnistica-suggestions",JSON.stringify(suggestions))}
function sortedWheel(list){var order={R1:1,R2:2,R:3,"11":4,"22":5};return list.sort(function(a,b){return(order[a.code]||9)-(order[b.code]||9)||a.person.localeCompare(b.person)})}
function originalWheel(){return sortedWheel(people().map(function(p){var e=raw(p,wheelDate);return e&&!isOff(e.code)?{person:p,code:effective(p,wheelDate),original:p}:null}).filter(Boolean))}
function toolbar(){return "<div class='toolbar'>"+selectField("Persona",person,roster().map(function(p){return[p,p]}),"person")+selectField("Anno",year,[["2026","2026"],["2027","2027"],["2028","2028"],["2029","2029"],["2030","2030"],["2031","2031"],["2032","2032"]],"year")+selectField("Mese",month,monthOptions,"month")+"</div>"}
function table(items,updated,showChanges){var h="<div class='table'><table><thead><tr><th>Data</th><th>Giorno</th><th>Turno</th><th>Stato</th></tr></thead><tbody>";items.forEach(function(e){var code=effective(person,e.date),c=showChanges?changes.find(function(x){return x.person===person&&x.date===e.date&&x.status==="approved"}):null;h+="<tr class='"+(c?"changed ":"")+(e.date===wheelDate?"today-row ":"")+"'><td>"+e.date+"</td><td>"+e.day+"</td><td>"+tag(code)+"</td><td>"+(c?"<span class='changed-label'>Sostituito da "+escapeHtml(c.substitute)+"</span>":"<span class='muted'>"+(updated?"Originale":"Da prospetto")+"</span>")+"</td></tr>"});return h+"</tbody></table></div>"}
function wheelPanel(list,editable,showDate){list=list||wheel();if(editable===undefined)editable=canManage();if(showDate===undefined)showDate=true;var dateControl=showDate?dateInput():"<span class='wheel-date-static'>Giorno "+escapeHtml(wheelDate)+"</span>";var h="<section class='wheel-panel'><div class='wheel-head'><div><small>RUOTA DEL GIORNO</small><h3>"+escapeHtml(wheelDate)+"</h3><p>"+list.length+" piloti presenti · "+(editable?"turni modificabili dal Capo pilota":"turni senza modifiche")+"</p></div>"+dateControl+"</div><div class='wheel-table-wrap'><table class='wheel-table'><thead><tr><th>Turno</th><th>Pilota</th><th>Annotazioni</th></tr></thead><tbody>";list.forEach(function(e){var name=editable?"<input class='wheel-pilot-input' data-wheel-name='"+escapeHtml(e.original)+"' value='"+escapeHtml(e.person)+"' aria-label='Nome pilota per il turno "+escapeHtml(e.code)+"'>":"<strong>"+escapeHtml(e.person)+"</strong>";h+="<tr class='"+(e.original===person?"mine ":"")+(e.replaced?"replacement ":"")+"'><td>"+tag(e.code)+"</td><td>"+name+(e.replaced?"<small>sostituisce "+escapeHtml(e.original)+"</small>":"")+"</td><td class='hand-note'></td></tr>"});if(!list.length)h+="<tr><td colspan='3' class='empty'>Nessun pilota in servizio per questa data.</td></tr>";return h+="</tbody></table></div><div class='wheel-legend'><span>R1 montante</span><span>R2 montante</span><span>11 guardia notturna</span><span>22 smontante alle 22</span><span>R ruota</span>"+(editable?"<span class='edit-key'>Nomi modificabili dal Capo pilota</span>":"")+"</div></section>"}
function original(){app.innerHTML="<div class='content'><div class='intro'><div><h3>La ruota del giorno</h3><p>Questa è la ruota originale, senza sostituzioni approvate e senza correzioni manuali dei nomi.</p></div><div class='metric'><strong>"+people().length+"</strong><small>piloti attivi</small></div><div class='metric'><strong>"+originalWheel().length+"</strong><small>in servizio</small></div></div>"+wheelPanel(originalWheel(),false,true)+toolbar()+table(entries(),false,false)+"</div>"}
function updated(){var approved=changes.filter(function(c){return c.status==="approved"}).length;app.innerHTML="<div class='content'><div class='intro'><div><h3>Ruota aggiornata</h3><p>Le sostituzioni approvate cambiano il pilota presente, ma non il turno assegnato.</p></div><div class='metric'><strong>"+approved+"</strong><small>modifiche attive</small></div><div class='updated-actions'><button class='button secondary-button' id='toggleOriginalWheel'>Visualizza ruota originale</button></div></div><div class='updated-wheel-layout'><div class='updated-wheel-main'>"+wheelPanel(wheel(),canManage(),true)+"</div><aside class='original-wheel-drawer' id='originalWheelDrawer'>"+wheelPanel(originalWheel(),false,false)+"</aside></div>"+toolbar()+table(entries(),true,true)+"</div>"}
function suggestionCard(s){return"<article class='suggestion-card'><div><span class='status approved'>"+escapeHtml(s.type)+"</span><b>"+escapeHtml(s.author)+"</b><small>"+escapeHtml(s.createdAt)+"</small></div><p>"+escapeHtml(s.text)+"</p></article>"}
function suggestionsPage(){if(!canSuggest())return original();var mine=suggestions.filter(function(s){return s.author===person});app.innerHTML="<div class='content'><div class='intro'><div><h3>Suggerimenti, variazioni &amp; Bestemmie</h3><p>Spazio riservato ai Sottocapi. I messaggi inseriti qui saranno raccolti nella sezione del Capo pilota.</p></div></div><div class='suggestion-form'><label class='field'>Tipo<select id='suggestionType'><option>Suggerimento</option><option>Variazione</option><option>Bestemmia</option></select></label><label class='field suggestion-text-field'>Messaggio<textarea id='suggestionText' rows='5' placeholder='Scrivi qui...'></textarea></label><button class='button' id='saveSuggestion'>Invia a GRAN</button></div><div class='section'><h3>I miei messaggi</h3></div><div class='suggestions-list'>"+(mine.length?mine.slice().reverse().map(suggestionCard).join(""):"<div class='empty'>Nessun messaggio inserito.</div>")+"</div></div>"}
function receivedSuggestionsPage(){if(!isGranara())return original();app.innerHTML="<div class='content'><div class='intro'><div><h3>Suggerimenti ricevuti</h3><p>Messaggi inviati dai Sottocapi, visibili solo a GRAN.</p></div><div class='metric'><strong>"+suggestions.length+"</strong><small>messaggi ricevuti</small></div></div><div class='suggestions-list'>"+(suggestions.length?suggestions.slice().reverse().map(suggestionCard).join(""):"<div class='empty'>Nessun suggerimento ricevuto.</div>")+"</div></div>"}
function render(){if(!Object.keys(schedule).length){app.innerHTML="<div class='empty'>Caricamento turnistica...</div>";return}if(!sessionStorage.getItem("turnistica-user")){login();return}document.querySelector("#userBadge").textContent=person.slice(0,2);var mn=document.querySelector("#managementNav"),sn=document.querySelector("#suggestionsNav"),rn=document.querySelector("#receivedSuggestionsNav");if(mn)mn.style.display=canManage()?"flex":"none";if(sn)sn.style.display=canSuggest()?"flex":"none";if(rn)rn.style.display=isGranara()?"flex":"none";if(page==="original")original();else if(page==="changes")(canWrite()?changePage:readonlyChanges)();else if(page==="management")(canManage()?managementPage:original)();else if(page==="suggestions")suggestionsPage();else if(page==="received-suggestions")receivedSuggestionsPage();else updated();wire()}
function setPageTitle(){var labels={original:"Turnistica originale",changes:"Variazioni di turno",updated:"Turnistica aggiornata",management:"Gestione autorizzazioni",suggestions:"Suggerimenti, variazioni & Bestemmie","received-suggestions":"Suggerimenti ricevuti"};if(title)title.textContent=labels[page]||"Turnistica"}
document.addEventListener("click",function(ev){var target=ev.target;if(!target)return;if(target.id==="suggestionsNav"||target.closest&&target.closest("#suggestionsNav")){page="suggestions";setPageTitle();render()}if(target.id==="receivedSuggestionsNav"||target.closest&&target.closest("#receivedSuggestionsNav")){page="received-suggestions";setPageTitle();render()}if(target.id==="toggleOriginalWheel"){var drawer=document.querySelector("#originalWheelDrawer");if(drawer){var visible=drawer.classList.toggle("visible");target.textContent=visible?"Nascondi ruota originale":"Visualizza ruota originale"}}if(target.id==="saveSuggestion"){var text=document.querySelector("#suggestionText"),type=document.querySelector("#suggestionType");if(!text||!text.value.trim())return; suggestions.push({id:Date.now().toString(),author:person,type:type.value,text:text.value.trim(),createdAt:new Date().toLocaleString("it-IT")});suggestionsSave();render()}});
document.querySelectorAll("nav button").forEach(function(b){b.addEventListener("click",function(){page=b.dataset.page;setPageTitle()})});
