import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.surface,
    gap: 12,
  },
  titleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  title: { fontFamily: "Inter_700Bold", fontSize: 24, color: Colors.text },
  tabs: { flexDirection: "row", gap: 8 },
  tab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  activeTab: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  tabText: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.textSecondary },
  activeTabText: { color: "#fff" },
  content: { flex: 1 },
  list: { padding: 16, paddingBottom: 100 },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 30,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.accent,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: Colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 20,
    maxHeight: "90%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  modalTitle: { fontFamily: "Inter_700Bold", fontSize: 18, color: Colors.text },
  inputGroup: { marginBottom: 16, gap: 8 },
  label: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.textSecondary },
  input: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    padding: 12,
    color: Colors.text,
    fontFamily: "Inter_400Regular",
  },
  imagePicker: {
    aspectRatio: 16 / 9,
    backgroundColor: Colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  previewImage: { width: "100%", height: "100%" },
  submitBtn: {
    backgroundColor: Colors.accent,
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
    marginBottom: 40,
  },
  submitBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 16, color: "#fff" },
  bulkUploadInfo: {
    backgroundColor: Colors.surface,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 16,
  },
  bulkInfoText: { fontFamily: "Inter_400Regular", fontSize: 13, color: Colors.textSecondary, lineHeight: 18 },
  bulkImageGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  bulkImageItem: { width: 60, height: 60, borderRadius: 4, backgroundColor: Colors.border },
  progressOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  progressBox: { backgroundColor: Colors.surface, padding: 20, borderRadius: 12, alignItems: "center", gap: 12, minWidth: 200 },
  progressBar: { width: "100%", height: 4, backgroundColor: Colors.border, borderRadius: 2, overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: Colors.accent },
  progressText: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.text },
  settingsSection: { marginBottom: 20, gap: 12 },
  settingsSectionTitle: { fontFamily: "Inter_600SemiBold", fontSize: 15, color: Colors.text },
  modeOptions: { flexDirection: "row", gap: 10 },
  modeBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
  },
  modeBtnActive: { backgroundColor: Colors.accent + "15", borderColor: Colors.accent },
  modeText: { fontFamily: "Inter_500Medium", fontSize: 14, color: Colors.textSecondary },
  modeTextActive: { color: Colors.accent },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: Colors.error + "15",
    gap: 12,
  },
  errorBannerText: { flex: 1, fontFamily: "Inter_500Medium", fontSize: 13, color: Colors.error },
  errorBannerBtn: {
    backgroundColor: Colors.error,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
  },
  errorBannerBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: "#fff" },
  cacheStats: {
    paddingHorizontal: 16,
    paddingVertical: 4,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  cacheStatsText: { fontFamily: "Inter_400Regular", fontSize: 10, color: Colors.textSecondary },
});
