import { StyleSheet, Platform } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  scModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  scModalCard: {
    width: "100%",
    maxWidth: 520,
    maxHeight: "85%",
    backgroundColor: Colors.background,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.border,
  },
  scModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  scModalTitle: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    color: Colors.text,
  },
  scModalBody: { paddingHorizontal: 14, paddingVertical: 12 },
  scStatusLine: { fontFamily: "Inter_500Medium", fontSize: 13, color: Colors.text, marginBottom: 8 },
  scSummary: { fontFamily: "Inter_400Regular", fontSize: 13, color: Colors.text, marginBottom: 10, lineHeight: 18 },
  scFixBox: { backgroundColor: Colors.surface, borderLeftWidth: 3, borderLeftColor: Colors.warning, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 6, marginBottom: 10 },
  scFixLabel: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: Colors.warning, marginBottom: 4, textTransform: "uppercase" },
  scFixText: { fontFamily: "Inter_400Regular", fontSize: 13, color: Colors.text, lineHeight: 18 },
  scAiBriefBox: {
    backgroundColor: Colors.surface,
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: Colors.accent,
  },
  scAiBriefLabel: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: Colors.textSecondary, marginBottom: 4, textTransform: "uppercase" },
  scAiBriefText: { fontFamily: "Inter_400Regular", fontSize: 13, color: Colors.text, lineHeight: 18 },
  scNoAi: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary, fontStyle: "italic", marginBottom: 12 },
  scCopiedHint: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: Colors.success, textAlign: "center", paddingBottom: 4 },
  scStepsLabel: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: Colors.textSecondary, marginBottom: 6, marginTop: 4, textTransform: "uppercase" },
  scStepRow: { flexDirection: "row", alignItems: "flex-start", gap: 8, paddingVertical: 6 },
  scStepName: { fontFamily: "Inter_500Medium", fontSize: 13, color: Colors.text },
  scStepDur: { fontFamily: "Inter_400Regular", fontSize: 11, color: Colors.textSecondary },
  scStepMsg: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.error, marginTop: 2 },
  scModalFooter: {
    flexDirection: "row",
    gap: 8,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  scFooterBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: "center",
  },
  scFooterBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: "#fff" },
  container: { flex: 1, backgroundColor: Colors.background },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.error + "18",
    borderBottomWidth: 1,
    borderBottomColor: Colors.error + "44",
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
  },
  errorBannerText: {
    flex: 1,
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: Colors.error,
  },
  errorBannerRetry: {
    padding: 2,
  },
  fab: {
    position: "absolute",
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    ...Platform.select({
      ios: { shadowColor: "#000", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 5 },
      android: {},
      web: { boxShadow: "0px 3px 5px rgba(0,0,0,0.3)" },
    }),
  },
  fabFolder: {
    right: 88,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  createModalContainer: {
    flex: 1,
    backgroundColor: Colors.background,
    padding: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "flex-end",
  },
  settingsContent: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "60%",
  },
  overlayBg: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
});
