import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  content: { padding: 16 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: Colors.background },
  errorText: { fontFamily: "Inter_400Regular", fontSize: 14, color: "#ef4444", textAlign: "center", paddingHorizontal: 24 },
  envBanner: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#F59E0B22", borderWidth: 1, borderColor: "#F59E0B44", borderRadius: 10, padding: 12, marginBottom: 16 },
  envBannerText: { fontFamily: "Inter_400Regular", fontSize: 13, color: "#F59E0B", flex: 1 },
  envBannerValue: { fontFamily: "Inter_700Bold" },
  sectionHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
  sectionTitle: { fontFamily: "Inter_700Bold", fontSize: 15, color: Colors.text },
  card: { backgroundColor: Colors.surface, borderRadius: 16, borderWidth: 1, borderColor: Colors.border, padding: 16, marginBottom: 12 },
  cardInactive: { opacity: 0.6 },
  cardRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconBadge: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center" },
  cardInfo: { flex: 1, gap: 4 },
  cardTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  positionBadge: { width: 20, height: 20, borderRadius: 10, backgroundColor: Colors.accent, alignItems: "center", justifyContent: "center" },
  positionText: { fontFamily: "Inter_700Bold", fontSize: 11, color: "#000" },
  cardLabel: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.text },
  cardLabelInactive: { color: Colors.textSecondary },
  statusRow: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
  badge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, backgroundColor: "#22C55E22" },
  badgeWarn: { backgroundColor: "#F59E0B22" },
  badgeTextOk: { fontFamily: "Inter_400Regular", fontSize: 11, color: "#22C55E" },
  badgeTextWarn: { fontFamily: "Inter_400Regular", fontSize: 11, color: "#F59E0B" },
  cardActions: { alignItems: "center" },
  toggleBtn: { padding: 4 },
  toggleBtnActive: {},
  cardFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: Colors.border },
  cardFooterSimple: { justifyContent: "flex-end" },
  orderBtns: { flexDirection: "row", gap: 4 },
  orderBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border, alignItems: "center", justifyContent: "center" },
  orderBtnDisabled: { opacity: 0.4 },
  testBtn: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: `${Colors.accent}22`, borderWidth: 1, borderColor: `${Colors.accent}44`, minWidth: 60, justifyContent: "center" },
  testBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: Colors.accent },
  testResult: { marginTop: 10, borderRadius: 8, padding: 10 },
  testResultOk: { backgroundColor: "#22C55E22" },
  testResultFail: { backgroundColor: "#ef444422" },
  testResultText: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.text },
  testResultSubline: { marginTop: 4, opacity: 0.85 },
  bodyRawBox: { marginTop: 6, backgroundColor: Colors.background, borderRadius: 6, padding: 8, borderWidth: 1, borderColor: Colors.border },
  bodyRawText: { fontFamily: "Inter_400Regular", fontSize: 11, color: Colors.textSecondary, fontVariant: ["tabular-nums"] },
  diagnoseBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 4, marginBottom: 12, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: `${Colors.accent}44`, backgroundColor: `${Colors.accent}11` },
  diagnoseBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.accent },
  diagReport: { backgroundColor: Colors.surface, borderRadius: 14, borderWidth: 1, borderColor: Colors.border, padding: 14, marginBottom: 12 },
  diagReportHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
  diagReportTitle: { fontFamily: "Inter_700Bold", fontSize: 14, color: Colors.text, flex: 1 },
  copyLogBtn: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border },
  copyLogText: { fontFamily: "Inter_500Medium", fontSize: 12, color: Colors.textSecondary },
  diagStep: { flexDirection: "row", gap: 8, paddingVertical: 8 },
  diagStepBorder: { borderTopWidth: 1, borderTopColor: Colors.border },
  diagStepIcon: { fontSize: 14, lineHeight: 20 },
  diagStepBody: { flex: 1, gap: 2 },
  diagStepLabel: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.text },
  diagStepLatency: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  diagStepDetail: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  resetBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 8, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.surface },
  resetBtnDisabled: { opacity: 0.5 },
  resetBtnText: { fontFamily: "Inter_500Medium", fontSize: 14, color: Colors.textSecondary },
  savingBanner: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 12 },
  savingText: { fontFamily: "Inter_400Regular", fontSize: 13, color: Colors.textSecondary },
  tokenWarnBanner: { flexDirection: "row", alignItems: "flex-start", gap: 6, marginTop: 6, backgroundColor: "#F59E0B18", borderWidth: 1, borderColor: "#F59E0B44", borderRadius: 8, padding: 8 },
  tokenWarnText: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: "#F59E0B" },
  tokenWarnNote: { fontFamily: "Inter_400Regular", fontSize: 11, color: "#F59E0B", opacity: 0.85, marginTop: 1 },
  watchdogCard: { borderRadius: 12, borderWidth: 1, padding: 12, marginBottom: 14 },
  watchdogRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  watchdogTitleRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap" },
  watchdogStatus: { fontFamily: "Inter_700Bold", fontSize: 13 },
  watchdogOffline: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  watchdogMeta: { fontFamily: "Inter_400Regular", fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  watchdogRefresh: { fontFamily: "Inter_400Regular", fontSize: 10, color: Colors.textSecondary },
  watchdogRestartRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#F59E0B33" },
  watchdogRestartText: { fontFamily: "Inter_400Regular", fontSize: 11, color: "#F59E0B", flex: 1 },
});
