import type { AdminGroup } from "./admin-types";

export const adminGroupsPart2: AdminGroup[] = [
  {
    title: "Sistema",
    headerIcon: "settings",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "ai-hub",
        label: "Hub AI",
        icon: "robot-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ai-hub",
        accentColor: "#FF6600",
        keywords: ["ai", "hub", "intelligenza artificiale", "llm", "groq", "gemini", "openai", "ollama", "machine learning", "modello", "model", "prompt", "token", "api key ai", "costo ai", "utilizzo ai", "anthropic", "claude"],
      },
      {
        key: "ai-assistant",
        label: "AI Assistant Utenti",
        icon: "account-question-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ai-assistant",
        accentColor: "#FF6600",
        keywords: ["ai", "assistant", "assistente", "chatbot", "utente", "supporto", "help", "bot", "widget", "galleggiante", "bubble", "floating", "popup ai", "bollicina", "chat ai", "conversazione ai"],
      },
      {
        key: "system-health",
        label: "AI System Watchdog",
        icon: "shield-check",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/system-health",
        accentColor: "#22c55e",
        keywords: ["ai", "watchdog", "sistema", "system", "health", "salute", "anomalia", "alert", "allerta", "monitor ai", "errore ai", "ai error", "fallback", "quota", "rate limit", "rilevamento anomalie", "anomaly detection"],
      },
      {
        key: "whisper-config",
        label: "Voce & Trascrizione",
        icon: "microphone-settings",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/whisper-config",
        accentColor: "#8B5CF6",
        keywords: ["whisper", "voce", "voice", "trascrizione", "transcription", "audio", "microfono", "speech", "stt", "riconoscimento vocale", "speech recognition", "nota vocale", "vocal note", "lingua audio", "modello audio"],
      },
      {
        key: "settings",
        label: "Impostazioni",
        icon: "settings",
        iconSet: "MaterialIcons",
        route: "/admin/settings",
        keywords: ["impostazioni", "settings", "configurazione", "config", "preferenze", "preferences", "opzioni", "widget", "galleggiante", "floating", "bubble", "notifica", "notifiche", "push", "push notification", "avviso", "alert", "popup", "toggle", "parametri globali", "app config"],
      },
      {
        key: "legal-docs",
        label: "Manualistica",
        icon: "document-text-outline",
        iconSet: "Ionicons",
        route: "/admin/legal-docs",
        accentColor: "#0EA5E9",
        keywords: ["manuale", "docs", "documentazione", "legale", "legal", "privacy policy", "termini", "terms", "gdpr", "guida", "guide", "tutorial", "faq", "istruzioni", "help", "accordo", "agreement", "contratto", "cookie policy"],
      },
      {
        key: "privacy",
        label: "Gestione Privacy",
        icon: "shield-lock",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/privacy",
        accentColor: "#4CAF50",
        keywords: ["privacy", "gdpr", "dati personali", "consenso", "consent", "trattamento dati", "rgpd", "cancellazione account", "account deletion", "diritto oblio", "right to erasure", "portabilità", "data portability", "cookie", "opt-out", "dpo"],
      },
      {
        key: "invite-codes",
        label: "Codici Invito",
        icon: "gift",
        iconSet: "Ionicons",
        route: "/admin/invite-codes",
        keywords: ["codice", "invito", "invite", "code", "referral", "accesso", "registrazione", "beta", "token invito", "link invito", "invite link", "chiave accesso", "access key", "waitlist", "lista d'attesa", "early access", "accesso anticipato", "scadenza codice"],
      },
      {
        key: "backup",
        label: "Backup automatici",
        icon: "cloud-upload",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/backup",
        keywords: ["backup", "automatico", "salvataggio", "cloud", "ripristino", "restore", "sicurezza dati", "snapshot", "dump", "pg_dump", "frequenza", "pianificato", "scheduled", "google drive", "copia dati", "ultimo backup"],
      },
      {
        key: "backup-preview",
        label: "Esplora Backup",
        icon: "database-search",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/backup-preview",
        accentColor: "#F59E0B",
        keywords: ["backup", "esplora", "explore", "ripristino", "restore", "file backup", "storico backup", "lista backup", "download backup", "contenuto backup", "dati salvati", "visualizza backup", "anteprima backup"],
      },
      {
        key: "exports",
        label: "Export Dati",
        icon: "database-export",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/exports",
        accentColor: "#10B981",
        keywords: ["export", "esporta", "dati", "data", "csv", "json", "download", "estrazione", "excel", "xlsx", "dump dati", "scarica", "report", "estrai utenti", "big data", "file esportazione"],
      },
      {
        key: "tags",
        label: "Sistema Tag",
        icon: "tag-multiple",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/tags",
        accentColor: "#9C27B0",
        keywords: ["tag", "etichetta", "label", "hashtag", "categoria", "classificazione", "filtro", "filter", "cerca per tag", "aggiungi tag", "rimuovi tag", "trending tag", "gestione tag"],
      },
      {
        key: "text-aliases",
        label: "Alias Testo",
        icon: "spellcheck",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/text-aliases",
        accentColor: "#FF9800",
        keywords: ["alias", "testo", "text", "sinonimo", "abbreviazione", "shortcut", "sostituzione", "soprannome", "nickname", "parola chiave", "keyword", "mappatura", "mapping", "dizionario", "replace"],
      },
      {
        key: "tabella-lingue",
        label: "Tabella Lingue",
        icon: "table-large",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/tabella-lingue",
        accentColor: "#9C27B0",
        keywords: ["traduzione", "translate", "lingua", "language", "localizzazione", "i18n", "l10n", "internazionalizzazione", "stringa", "string", "chiave", "key", "testo", "en", "it", "de", "fr", "es", "multi-lingua", "tabella", "table", "locale", "sincronizza", "sync", "ai complete", "applica", "mancanti"],
      },
      {
        key: "maps",
        label: "Sistema Mappe",
        icon: "map-outline",
        iconSet: "Ionicons",
        route: "/admin/maps",
        accentColor: "#0EA5E9",
        keywords: ["mappa", "map", "mappe", "leaflet", "tile", "osm", "openstreetmap", "cartografia", "geocoding", "nominatim", "geocoder", "reverse geocoding", "coordinate", "zoom", "marker", "poi", "layer", "tileset"],
      },
    ],
  },
  {
    title: "Sistema Routing",
    headerIcon: "routes",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "routing-hub",
        label: "Hub Routing",
        icon: "view-dashboard-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-hub",
        accentColor: "#0EA5E9",
        keywords: ["routing", "hub", "percorso", "route", "navigazione", "dashboard routing", "overview", "panoramica", "statistiche routing", "percorso moto", "curvy", "grafico routing"],
      },
      {
        key: "routing-control",
        label: "Controllo Routing",
        icon: "tune-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-control",
        accentColor: "#9C27B0",
        keywords: ["routing", "controllo", "control", "kill switch", "toggle", "graphhopper", "valhalla", "motore routing", "osrm", "disabilita", "disable", "abilita", "enable", "profilo routing", "fallback routing", "routing engine"],
      },
      {
        key: "routing-health",
        label: "Routing Health",
        icon: "heart-pulse",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-health",
        accentColor: "#4CAF50",
        keywords: ["routing", "health", "salute", "stato", "status", "diagnostica routing", "graphhopper", "valhalla", "disponibilità", "availability", "ping", "latenza", "latency routing", "timeout routing", "errore motore"],
      },
      {
        key: "telemetry-users",
        label: "Sessioni Utenti",
        icon: "map-marker-path",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/telemetry-users",
        accentColor: "#22C55E",
        keywords: ["sessione", "session", "utente", "user", "percorso utente", "tracking", "tracciamento", "telemetria routing", "gps utente", "rotta", "traccia", "trace", "viaggio", "trip", "km percorsi", "distanza"],
      },
    ],
  },
  {
    title: "Laboratorio",
    headerIcon: "flask",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "sensors",
        label: "Sensori",
        icon: "chip",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/sensors",
        accentColor: "#FF9800",
        keywords: ["sensore", "sensor", "accelerometro", "giroscopio", "imu", "chip", "hardware", "telemetria moto", "piega", "lean angle", "inclinazione", "tilt", "g-force", "curva", "raw data", "moto sensor"],
      },
      {
        key: "telemetry",
        label: "Telemetria",
        icon: "chart-line",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/telemetry",
        accentColor: "#22C55E",
        keywords: ["telemetria", "telemetry", "dati moto", "sensori", "log dati", "metriche", "curva", "inclinazione", "analytics moto", "sessione moto", "log viaggio", "trip log", "velocità", "speed", "accelerazione", "frenata"],
      },
      {
        key: "ota",
        label: "Aggiornamenti OTA",
        icon: "cloud-download",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ota",
        accentColor: "#0EA5E9",
        keywords: ["ota", "aggiornamento", "update", "over the air", "deploy", "versione", "release", "publish", "expo update", "bundle", "js bundle", "patch", "hotfix", "canale", "channel", "rollout", "distribuzione", "rollback"],
      },
    ],
  },
  {
    title: "Diagnostica",
    headerIcon: "stethoscope",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "diagnostica-avanzata",
        label: "Diagnostica Avanzata",
        icon: "magnify-scan",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/diagnostica",
        accentColor: "#ef4444",
        keywords: ["diagnostica", "avanzata", "radiografia", "pipeline", "flusso", "monitor", "buchi", "check", "sonde", "telemetria pipeline", "matching check", "device report", "sistema completo", "full check", "end to end", "e2e", "integrazione", "stato sistema"],
      },
      {
        key: "diagnostic",
        label: "Diagnostica Locale",
        icon: "stethoscope",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/diagnostic",
        accentColor: "#22C55E",
        keywords: ["diagnostica", "diagnostic", "test", "self-test", "debug", "log", "errore", "sentry", "locale", "local", "connessione", "connection", "backend", "frontend", "api", "endpoint", "ping"],
      },
      {
        key: "diagnostic-reports",
        label: "Diagnostica Remota",
        icon: "remote-desktop",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/diagnostic-reports",
        accentColor: "#3B82F6",
        keywords: ["diagnostica", "remota", "report", "utenti", "online", "debug remoto", "trigger", "dispositivo remoto", "remote device", "crash remoto", "feedback", "segnalazione tecnica", "bug report", "invio diagnostica", "file json", "report file", "scarica report", "download diagnostica", "file diagnostica", "report su file", "json files", "esplora report", "filesystem diagnostica"],
      },
    ],
  },
];
