import type { AdminGroup } from "./admin-types";

export const OPEN_BY_DEFAULT = new Set<string>();

export const adminGroups: AdminGroup[] = [
  {
    title: "Utenti",
    headerIcon: "people",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "users",
        label: "Utenti",
        icon: "people",
        iconSet: "MaterialIcons",
        route: "/admin/users",
        keywords: ["utente", "user", "account", "profilo", "profile", "ban", "sospendi", "sospensione", "blocca", "block", "registrazione", "lista utenti"],
      },
      {
        key: "stregatti",
        label: "Stregatti",
        icon: "robot",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/stregatti",
        keywords: ["stregatto", "bot", "robot", "fake", "simulato", "utente finto", "seed"],
      },
      {
        key: "blocks",
        label: "Blocchi",
        icon: "ban",
        iconSet: "Ionicons",
        route: "/admin/blocks",
        keywords: ["blocco", "block", "ban", "sospensione", "bannato", "banned", "sospeso"],
      },
    ],
  },
  {
    title: "Report",
    headerIcon: "flag-variant",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "reports-hub",
        label: "Hub Report",
        icon: "view-dashboard-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-hub",
        accentColor: "#FF3B30",
        keywords: ["segnalazione", "report", "hub", "dashboard", "reclamo", "abuso"],
      },
      {
        key: "reports",
        label: "Coda Segnalazioni",
        icon: "flag",
        iconSet: "MaterialIcons",
        route: "/admin/reports",
        accentColor: "#FF9500",
        keywords: ["segnalazione", "report", "coda", "queue", "flag", "revisione", "moderazione"],
      },
      {
        key: "reports-by-category",
        label: "Per Categoria",
        icon: "shape-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-by-category",
        accentColor: "#0EA5E9",
        keywords: ["segnalazione", "report", "categoria", "category", "tipo", "type"],
      },
      {
        key: "reports-by-role",
        label: "Per Ruolo",
        icon: "account-group-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-by-role",
        accentColor: "#10B981",
        keywords: ["segnalazione", "report", "ruolo", "role", "moderatore", "admin"],
      },
      {
        key: "reports-patterns",
        label: "Pattern",
        icon: "chart-bell-curve",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-patterns",
        accentColor: "#E91E63",
        keywords: ["pattern", "analisi", "trend", "grafico", "chart", "segnalazione ricorrente"],
      },
      {
        key: "false-reports",
        label: "Falsi Report",
        icon: "shield-alert-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/false-reports",
        accentColor: "#9C27B0",
        keywords: ["falso", "false", "spam", "abuso segnalazione", "false report", "report errato"],
      },
      {
        key: "active-bans",
        label: "Ban Attivi",
        icon: "account-cancel-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/active-bans",
        accentColor: "#FF3B30",
        keywords: ["ban", "bannato", "sospeso", "sospensione", "blocco", "attivo", "active"],
      },
      {
        key: "moderator-logs",
        label: "Log Moderatori",
        icon: "shield-account-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/moderator-logs",
        accentColor: "#6366F1",
        keywords: ["log", "moderatore", "moderazione", "storico", "history", "audit", "azioni admin"],
      },
      {
        key: "reports-thresholds",
        label: "Soglie & Policy",
        icon: "tune-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-thresholds",
        accentColor: "#22C55E",
        keywords: ["soglia", "threshold", "policy", "regola", "rule", "limite", "limit", "configurazione moderazione"],
      },
    ],
  },
  {
    title: "Contenuti",
    headerIcon: "layers",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "workshops",
        label: "Officine",
        icon: "store",
        iconSet: "MaterialIcons",
        route: "/admin/workshops",
        keywords: ["officina", "workshop", "meccanico", "negozio", "shop", "riparazione", "garage"],
      },
      {
        key: "motoclubs",
        label: "Clubs",
        icon: "shield",
        iconSet: "Ionicons",
        route: "/admin/motoclubs",
        keywords: ["club", "motoclub", "gruppo", "community", "associazione", "gang", "biker"],
      },
      {
        key: "eventi",
        label: "Raduni",
        icon: "calendar",
        iconSet: "Ionicons",
        route: "/admin/eventi",
        keywords: ["evento", "event", "raduno", "meeting", "incontro", "calendario", "gita", "uscita"],
      },
      {
        key: "easter-eggs",
        label: "Easter Eggs",
        icon: "egg-easter",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/easter-eggs",
        keywords: ["easter egg", "segreto", "hidden", "nascosto", "badge", "achievement", "premi"],
      },
      {
        key: "ads",
        label: "Campagne",
        icon: "campaign",
        iconSet: "MaterialIcons",
        route: "/admin/ads",
        keywords: ["campagna", "ads", "pubblicità", "advertising", "banner", "promozione", "sponsor"],
      },
    ],
  },
  {
    title: "Monitoraggio",
    headerIcon: "bar-chart",
    headerIconSet: "Ionicons",
    items: [
      {
        key: "analytics",
        label: "Analytics",
        icon: "analytics",
        iconSet: "MaterialIcons",
        route: "/admin/analytics",
        keywords: ["analytics", "statistiche", "stats", "metriche", "dati", "grafico", "chart", "kpi"],
      },
      {
        key: "performance",
        label: "Performance",
        icon: "speedometer",
        iconSet: "Ionicons",
        route: "/admin/performance",
        keywords: ["performance", "prestazioni", "velocità", "speed", "latenza", "latency", "benchmark"],
      },
      {
        key: "gps-errors",
        label: "GPS Error Log",
        icon: "location-sharp",
        iconSet: "Ionicons",
        route: "/admin/gps-errors",
        keywords: ["gps", "errore", "error", "log", "posizione", "location", "geolocalizzazione"],
      },
      {
        key: "gps-rejections",
        label: "GPS Rifiutati",
        icon: "alert-circle",
        iconSet: "Ionicons",
        route: "/admin/gps-rejections",
        accentColor: "#FF9500",
        keywords: ["gps", "rifiutato", "rejected", "scartato", "posizione scartata", "filtro gps"],
      },
      {
        key: "db-debug",
        label: "DB Debug",
        icon: "database",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/db-debug",
        keywords: ["database", "db", "debug", "sql", "query", "postgres", "tabella"],
      },
      {
        key: "db-tables",
        label: "Dimensioni DB",
        icon: "database-settings",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/db-tables",
        keywords: ["database", "db", "dimensione", "size", "spazio", "storage", "tabella", "peso"],
      },
      {
        key: "system",
        label: "System Monitor",
        icon: "pulse-outline",
        iconSet: "Ionicons",
        route: "/admin/system",
        accentColor: "#FF4444",
        keywords: ["sistema", "system", "monitor", "cpu", "ram", "memoria", "server", "risorse", "health"],
      },
      {
        key: "moderator-logs",
        label: "Log Moderatori",
        icon: "shield-account-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/moderator-logs",
        keywords: ["log", "moderatore", "moderazione", "storico", "history", "audit", "azioni admin"],
      },
      {
        key: "crash-logs",
        label: "Log Riavvii",
        icon: "phone-alert",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/crash-logs",
        accentColor: "#FF6B35",
        keywords: ["crash", "riavvio", "restart", "log", "errore app", "crash report", "stability"],
      },
      {
        key: "visitatori",
        label: "Visitatori Sito",
        icon: "web",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/visitatori",
        accentColor: "#22C55E",
        keywords: ["visitatore", "visitor", "sito", "web", "landing", "traffico", "traffic", "accessi"],
      },
      {
        key: "device-stats",
        label: "Dispositivi",
        icon: "cellphone-check",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/device-stats",
        accentColor: "#6366F1",
        keywords: ["dispositivo", "device", "telefono", "phone", "ios", "android", "versione app", "client"],
      },
    ],
  },
  {
    title: "Marketing",
    headerIcon: "email-newsletter",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "newsletter",
        label: "Newsletter",
        icon: "email-newsletter",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/newsletter",
        accentColor: "#2196F3",
        keywords: ["newsletter", "email", "mailing", "iscritti", "subscriber", "invio", "comunicazione"],
      },
    ],
  },
  {
    title: "Matching",
    headerIcon: "link-variant",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "matching-hub",
        label: "Hub Matching",
        icon: "view-dashboard-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/matching-hub",
        accentColor: "#0EA5E9",
        keywords: ["matching", "hub", "dashboard", "accoppiamento", "suggerimenti", "recommendations"],
      },
      {
        key: "match-engine",
        label: "Motore Matching",
        icon: "engine",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-engine",
        accentColor: "#FF9500",
        keywords: ["matching", "motore", "engine", "algoritmo", "algorithm", "ml", "intelligenza artificiale"],
      },
      {
        key: "match-rules",
        label: "Regole Matching",
        icon: "table-large",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-rules",
        accentColor: "#10B981",
        keywords: ["matching", "regola", "rule", "configurazione", "peso", "score", "criterio"],
      },
      {
        key: "match-inspector",
        label: "Match Inspector",
        icon: "account-search",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-inspector",
        accentColor: "#2196F3",
        keywords: ["matching", "inspector", "ispezione", "debug match", "coppia", "pair", "analisi match"],
      },
      {
        key: "match-control",
        label: "Controllo Sistema",
        icon: "tune-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-control",
        accentColor: "#9C27B0",
        keywords: ["matching", "controllo", "control", "sistema", "toggle", "kill switch", "abilitazione"],
      },
      {
        key: "match-health",
        label: "Match Health",
        icon: "heart-pulse",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-health",
        accentColor: "#4CAF50",
        keywords: ["matching", "health", "salute", "stato", "status", "diagnostica"],
      },
      {
        key: "matching-telemetry",
        label: "Telemetria",
        icon: "chart-line",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/matching-telemetry",
        accentColor: "#22C55E",
        keywords: ["matching", "telemetria", "telemetry", "metriche", "dati", "statistiche", "log matching"],
      },
      {
        key: "ab",
        label: "A/B Esperimenti",
        icon: "flask-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ab",
        accentColor: "#E91E63",
        keywords: ["ab test", "esperimento", "experiment", "split test", "variante", "variant", "test"],
      },
    ],
  },
  {
    title: "Sistema",
    headerIcon: "settings",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "ai-hub",
        label: "Hub AI",
        icon: "robot-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ai-hub",
        accentColor: "#FF6600",
        keywords: ["ai", "hub", "intelligenza artificiale", "llm", "groq", "gemini", "openai", "ollama", "machine learning"],
      },
      {
        key: "ai-assistant",
        label: "AI Assistant Utenti",
        icon: "account-question-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ai-assistant",
        accentColor: "#FF6600",
        keywords: ["ai", "assistant", "assistente", "chatbot", "utente", "supporto", "help", "bot", "widget", "galleggiante", "bubble", "floating", "popup ai", "bollicina"],
      },
      {
        key: "system-health",
        label: "AI System Watchdog",
        icon: "shield-check",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/system-health",
        accentColor: "#22c55e",
        keywords: ["ai", "watchdog", "sistema", "system", "health", "salute", "anomalia", "alert", "allerta", "monitor ai"],
      },
      {
        key: "whisper-config",
        label: "Voce & Trascrizione",
        icon: "microphone-settings",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/whisper-config",
        accentColor: "#8B5CF6",
        keywords: ["whisper", "voce", "voice", "trascrizione", "transcription", "audio", "microfono", "speech", "stt"],
      },
      {
        key: "settings",
        label: "Impostazioni",
        icon: "settings",
        iconSet: "MaterialIcons",
        route: "/admin/settings",
        keywords: ["impostazioni", "settings", "configurazione", "config", "preferenze", "preferences", "opzioni", "widget", "galleggiante", "floating", "bubble", "notifica", "notifiche", "push", "push notification", "avviso", "alert", "popup"],
      },
      {
        key: "legal-docs",
        label: "Manualistica",
        icon: "document-text-outline",
        iconSet: "Ionicons",
        route: "/admin/legal-docs",
        accentColor: "#0EA5E9",
        keywords: ["manuale", "docs", "documentazione", "legale", "legal", "privacy policy", "termini", "terms", "gdpr"],
      },
      {
        key: "privacy",
        label: "Gestione Privacy",
        icon: "shield-lock",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/privacy",
        accentColor: "#4CAF50",
        keywords: ["privacy", "gdpr", "dati personali", "consenso", "consent", "trattamento dati", "rgpd"],
      },
      {
        key: "invite-codes",
        label: "Codici Invito",
        icon: "gift",
        iconSet: "Ionicons",
        route: "/admin/invite-codes",
        keywords: ["codice", "invito", "invite", "code", "referral", "accesso", "registrazione", "beta"],
      },
      {
        key: "backup",
        label: "Backup automatici",
        icon: "cloud-upload",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/backup",
        keywords: ["backup", "automatico", "salvataggio", "cloud", "ripristino", "restore", "sicurezza dati"],
      },
      {
        key: "backup-preview",
        label: "Esplora Backup",
        icon: "database-search",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/backup-preview",
        accentColor: "#F59E0B",
        keywords: ["backup", "esplora", "explore", "ripristino", "restore", "file backup", "storico backup"],
      },
      {
        key: "exports",
        label: "Export Dati",
        icon: "database-export",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/exports",
        accentColor: "#10B981",
        keywords: ["export", "esporta", "dati", "data", "csv", "json", "download", "estrazione"],
      },
      {
        key: "tags",
        label: "Sistema Tag",
        icon: "tag-multiple",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/tags",
        accentColor: "#9C27B0",
        keywords: ["tag", "etichetta", "label", "hashtag", "categoria", "classificazione"],
      },
      {
        key: "text-aliases",
        label: "Alias Testo",
        icon: "spellcheck",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/text-aliases",
        accentColor: "#FF9800",
        keywords: ["alias", "testo", "text", "sinonimo", "abbreviazione", "shortcut", "sostituzione"],
      },
    ],
  },
  {
    title: "Traduzioni",
    headerIcon: "translate",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "traduzioni",
        label: "Traduzioni",
        icon: "translate",
        iconSet: "MaterialIcons",
        route: "/admin/traduzioni",
        accentColor: "#9C27B0",
        keywords: ["traduzione", "translate", "lingua", "language", "localizzazione", "i18n", "l10n", "internazionalizzazione"],
      },
      {
        key: "tabella-lingue",
        label: "Tabella Lingue",
        icon: "table-large",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/tabella-lingue",
        accentColor: "#9C27B0",
        keywords: ["lingua", "language", "tabella", "table", "locale", "paese", "country", "flag"],
      },
    ],
  },
  {
    title: "Sistema Mappe",
    headerIcon: "map-outline",
    headerIconSet: "Ionicons",
    items: [
      {
        key: "maps",
        label: "Sistema Mappe",
        icon: "map-outline",
        iconSet: "Ionicons",
        route: "/admin/maps",
        accentColor: "#0EA5E9",
        keywords: ["mappa", "map", "mappe", "leaflet", "tile", "osm", "openstreetmap", "cartografia", "geocoding"],
      },
    ],
  },
  {
    title: "Sistema Routing",
    headerIcon: "routes",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "routing-hub",
        label: "Hub Routing",
        icon: "view-dashboard-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-hub",
        accentColor: "#0EA5E9",
        keywords: ["routing", "hub", "percorso", "route", "navigazione", "dashboard routing"],
      },
      {
        key: "routing-control",
        label: "Controllo Routing",
        icon: "tune-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-control",
        accentColor: "#9C27B0",
        keywords: ["routing", "controllo", "control", "kill switch", "toggle", "graphhopper", "valhalla", "motore routing"],
      },
      {
        key: "routing-health",
        label: "Routing Health",
        icon: "heart-pulse",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-health",
        accentColor: "#4CAF50",
        keywords: ["routing", "health", "salute", "stato", "status", "diagnostica routing", "graphhopper", "valhalla"],
      },
      {
        key: "telemetry-users",
        label: "Sessioni Utenti",
        icon: "map-marker-path",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/telemetry-users",
        accentColor: "#22C55E",
        keywords: ["sessione", "session", "utente", "user", "percorso utente", "tracking", "tracciamento", "telemetria routing"],
      },
    ],
  },
  {
    title: "Laboratorio",
    headerIcon: "flask",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "sensors",
        label: "Sensori",
        icon: "chip",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/sensors",
        accentColor: "#FF9800",
        keywords: ["sensore", "sensor", "accelerometro", "giroscopio", "imu", "chip", "hardware", "telemetria moto"],
      },
      {
        key: "telemetry",
        label: "Telemetria",
        icon: "chart-line",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/telemetry",
        accentColor: "#22C55E",
        keywords: ["telemetria", "telemetry", "dati moto", "sensori", "log dati", "metriche", "curva", "inclinazione"],
      },
    ],
  },
  {
    title: "Controllo OTA",
    headerIcon: "cloud-download",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "ota",
        label: "Aggiornamenti OTA",
        icon: "cloud-download",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ota",
        accentColor: "#0EA5E9",
        keywords: ["ota", "aggiornamento", "update", "over the air", "deploy", "versione", "release", "publish"],
      },
    ],
  },
];
