import type { AdminGroup } from "./admin-types";

export const adminGroupsPart2: AdminGroup[] = [
  {
    title: "Sistema",
    headerIcon: "settings",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "ai-hub",
        label: "Hub AI",
        icon: "robot-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ai-hub",
        accentColor: "#FF6600",
        keywords: ["ai", "hub", "intelligenza artificiale", "llm", "groq", "gemini", "openai", "ollama", "machine learning"],
      },
      {
        key: "ai-assistant",
        label: "AI Assistant Utenti",
        icon: "account-question-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ai-assistant",
        accentColor: "#FF6600",
        keywords: ["ai", "assistant", "assistente", "chatbot", "utente", "supporto", "help", "bot", "widget", "galleggiante", "bubble", "floating", "popup ai", "bollicina"],
      },
      {
        key: "system-health",
        label: "AI System Watchdog",
        icon: "shield-check",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/system-health",
        accentColor: "#22c55e",
        keywords: ["ai", "watchdog", "sistema", "system", "health", "salute", "anomalia", "alert", "allerta", "monitor ai"],
      },
      {
        key: "whisper-config",
        label: "Voce & Trascrizione",
        icon: "microphone-settings",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/whisper-config",
        accentColor: "#8B5CF6",
        keywords: ["whisper", "voce", "voice", "trascrizione", "transcription", "audio", "microfono", "speech", "stt"],
      },
      {
        key: "settings",
        label: "Impostazioni",
        icon: "settings",
        iconSet: "MaterialIcons",
        route: "/admin/settings",
        keywords: ["impostazioni", "settings", "configurazione", "config", "preferenze", "preferences", "opzioni", "widget", "galleggiante", "floating", "bubble", "notifica", "notifiche", "push", "push notification", "avviso", "alert", "popup"],
      },
      {
        key: "legal-docs",
        label: "Manualistica",
        icon: "document-text-outline",
        iconSet: "Ionicons",
        route: "/admin/legal-docs",
        accentColor: "#0EA5E9",
        keywords: ["manuale", "docs", "documentazione", "legale", "legal", "privacy policy", "termini", "terms", "gdpr"],
      },
      {
        key: "privacy",
        label: "Gestione Privacy",
        icon: "shield-lock",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/privacy",
        accentColor: "#4CAF50",
        keywords: ["privacy", "gdpr", "dati personali", "consenso", "consent", "trattamento dati", "rgpd"],
      },
      {
        key: "invite-codes",
        label: "Codici Invito",
        icon: "gift",
        iconSet: "Ionicons",
        route: "/admin/invite-codes",
        keywords: ["codice", "invito", "invite", "code", "referral", "accesso", "registrazione", "beta"],
      },
      {
        key: "backup",
        label: "Backup automatici",
        icon: "cloud-upload",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/backup",
        keywords: ["backup", "automatico", "salvataggio", "cloud", "ripristino", "restore", "sicurezza dati"],
      },
      {
        key: "backup-preview",
        label: "Esplora Backup",
        icon: "database-search",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/backup-preview",
        accentColor: "#F59E0B",
        keywords: ["backup", "esplora", "explore", "ripristino", "restore", "file backup", "storico backup"],
      },
      {
        key: "exports",
        label: "Export Dati",
        icon: "database-export",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/exports",
        accentColor: "#10B981",
        keywords: ["export", "esporta", "dati", "data", "csv", "json", "download", "estrazione"],
      },
      {
        key: "tags",
        label: "Sistema Tag",
        icon: "tag-multiple",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/tags",
        accentColor: "#9C27B0",
        keywords: ["tag", "etichetta", "label", "hashtag", "categoria", "classificazione"],
      },
      {
        key: "text-aliases",
        label: "Alias Testo",
        icon: "spellcheck",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/text-aliases",
        accentColor: "#FF9800",
        keywords: ["alias", "testo", "text", "sinonimo", "abbreviazione", "shortcut", "sostituzione"],
      },
    ],
  },
  {
    title: "Traduzioni",
    headerIcon: "translate",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "traduzioni",
        label: "Traduzioni",
        icon: "translate",
        iconSet: "MaterialIcons",
        route: "/admin/traduzioni",
        accentColor: "#9C27B0",
        keywords: ["traduzione", "translate", "lingua", "language", "localizzazione", "i18n", "l10n", "internazionalizzazione"],
      },
      {
        key: "tabella-lingue",
        label: "Tabella Lingue",
        icon: "table-large",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/tabella-lingue",
        accentColor: "#9C27B0",
        keywords: ["lingua", "language", "tabella", "table", "locale", "paese", "country", "flag"],
      },
    ],
  },
  {
    title: "Sistema Mappe",
    headerIcon: "map-outline",
    headerIconSet: "Ionicons",
    items: [
      {
        key: "maps",
        label: "Sistema Mappe",
        icon: "map-outline",
        iconSet: "Ionicons",
        route: "/admin/maps",
        accentColor: "#0EA5E9",
        keywords: ["mappa", "map", "mappe", "leaflet", "tile", "osm", "openstreetmap", "cartografia", "geocoding"],
      },
    ],
  },
  {
    title: "Sistema Routing",
    headerIcon: "routes",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "routing-hub",
        label: "Hub Routing",
        icon: "view-dashboard-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-hub",
        accentColor: "#0EA5E9",
        keywords: ["routing", "hub", "percorso", "route", "navigazione", "dashboard routing"],
      },
      {
        key: "routing-control",
        label: "Controllo Routing",
        icon: "tune-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-control",
        accentColor: "#9C27B0",
        keywords: ["routing", "controllo", "control", "kill switch", "toggle", "graphhopper", "valhalla", "motore routing"],
      },
      {
        key: "routing-health",
        label: "Routing Health",
        icon: "heart-pulse",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/routing-health",
        accentColor: "#4CAF50",
        keywords: ["routing", "health", "salute", "stato", "status", "diagnostica routing", "graphhopper", "valhalla"],
      },
      {
        key: "telemetry-users",
        label: "Sessioni Utenti",
        icon: "map-marker-path",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/telemetry-users",
        accentColor: "#22C55E",
        keywords: ["sessione", "session", "utente", "user", "percorso utente", "tracking", "tracciamento", "telemetria routing"],
      },
    ],
  },
  {
    title: "Laboratorio",
    headerIcon: "flask",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "sensors",
        label: "Sensori",
        icon: "chip",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/sensors",
        accentColor: "#FF9800",
        keywords: ["sensore", "sensor", "accelerometro", "giroscopio", "imu", "chip", "hardware", "telemetria moto"],
      },
      {
        key: "telemetry",
        label: "Telemetria",
        icon: "chart-line",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/telemetry",
        accentColor: "#22C55E",
        keywords: ["telemetria", "telemetry", "dati moto", "sensori", "log dati", "metriche", "curva", "inclinazione"],
      },
    ],
  },
  {
    title: "Diagnostica",
    headerIcon: "stethoscope",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "diagnostic",
        label: "Diagnostica Locale",
        icon: "stethoscope",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/diagnostic",
        accentColor: "#22C55E",
        keywords: ["diagnostica", "diagnostic", "test", "self-test", "debug", "log", "errore", "sentry"],
      },
      {
        key: "diagnostic-reports",
        label: "Diagnostica Remota",
        icon: "remote-desktop",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/diagnostic-reports",
        accentColor: "#3B82F6",
        keywords: ["diagnostica", "remota", "report", "utenti", "online", "debug remoto", "trigger"],
      },
    ],
  },
  {
    title: "Controllo OTA",
    headerIcon: "cloud-download",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "ota",
        label: "Aggiornamenti OTA",
        icon: "cloud-download",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ota",
        accentColor: "#0EA5E9",
        keywords: ["ota", "aggiornamento", "update", "over the air", "deploy", "versione", "release", "publish"],
      },
    ],
  },
];
