/* eslint-disable @typescript-eslint/no-explicit-any */
import { StyleSheet } from "react-native";

export const makeStyles = (colors: any) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  section: { padding: 16 },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: colors.text },
  sectionSub: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  vacuumBtn: { flexDirection: "row", alignItems: "center", backgroundColor: colors.accent, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, gap: 6 },
  vacuumBtnDisabled: { opacity: 0.6 },
  vacuumBtnText: { color: "#fff", fontSize: 13, fontWeight: "600" },
  runningBanner: { flexDirection: "row", alignItems: "center", backgroundColor: colors.accent + "11", padding: 12, borderRadius: 8, gap: 10, marginBottom: 16, borderWidth: 1, borderColor: colors.accent + "33" },
  runningText: { fontSize: 12, color: colors.accent, flex: 1, fontWeight: "500" },
  lastVacuumRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 },
  lastVacuumText: { fontSize: 12, color: colors.textSecondary },
  lastVacuumValue: { color: colors.text, fontWeight: "600" },
  savedBanner: { flexDirection: "row", alignItems: "center", backgroundColor: (colors.success ?? "#22c55e") + "11", padding: 8, borderRadius: 6, gap: 6, marginBottom: 16 },
  savedBannerText: { fontSize: 11, color: colors.textSecondary },
  savedBannerValue: { color: colors.success ?? "#22c55e", fontWeight: "700" },
  tableSection: { marginTop: 8 },
  tableHeader: { flexDirection: "row", paddingHorizontal: 16, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.surface + "44" },
  colLabel: { fontSize: 10, fontWeight: "700", color: colors.textSecondary, textTransform: "uppercase" },
  colRight: { textAlign: "right", paddingLeft: 8 },
  colSaved: { flex: 1.2 },
  colMode: { flex: 1.5, paddingLeft: 8 },
  tableRow: { flexDirection: "row", paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, alignItems: "center" },
  tableRowFull: { backgroundColor: colors.accent + "08" },
  tableName: { fontSize: 13, color: colors.text, fontWeight: "500" },
  tableSize: { fontSize: 12, color: colors.textSecondary, flex: 1 },
  totalSize: { color: colors.text, fontWeight: "600" },
  savedPositive: { color: colors.success ?? "#22c55e", fontWeight: "600" },
  savedNeutral: { color: colors.textSecondary, opacity: 0.5 },
  modeBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, alignItems: "center" },
  modeBadgeAnalyze: { backgroundColor: colors.surface },
  modeBadgeFull: { backgroundColor: colors.accent + "22" },
  modeBadgeText: { fontSize: 8, fontWeight: "800" },
  modeBadgeTextAnalyze: { color: colors.textSecondary },
  modeBadgeTextFull: { color: colors.accent },
  bloatText: { fontSize: 9, fontWeight: "600", marginTop: 1 },
  bloatTextAnalyze: { color: colors.textSecondary },
  bloatTextFull: { color: colors.accent },
  errorBox: { padding: 40, alignItems: "center" },
  errorText: { color: colors.error, marginBottom: 16 },
  retryBtn: { padding: 12, backgroundColor: colors.surface, borderRadius: 8 },
  retryText: { color: colors.accent, fontWeight: "600" },
});
