import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  loadingContainer: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: Colors.background },
  errorText: { fontFamily: "Inter_400Regular", fontSize: 15, color: Colors.textSecondary },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 16,
  },
  refreshBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  refreshText: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.accent },
  recalcBtn: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    backgroundColor: Colors.accent,
    borderRadius: 12,
  },
  recalcText: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: "#fff" },
  deleteMatchesRow: {
    paddingHorizontal: 16,
    marginBottom: 16,
    gap: 8,
  },
  deleteMatchesTop: {},
  deleteMatchesBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.error,
  },
  deleteMatchesText: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.error },
  autoRecalcRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  autoRecalcSwitch: { transform: [{ scaleX: 0.85 }, { scaleY: 0.85 }] },
  autoRecalcLabel: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: Colors.textSecondary,
    flex: 1,
  },
  sectionTitle: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: Colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
});
