import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  section: { marginTop: 20, paddingHorizontal: 16 },
  sectionHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: Colors.text, marginBottom: 10 },
  cardRow: { flexDirection: "row", gap: 10 },
  statCard: { flex: 1, backgroundColor: Colors.surface, borderRadius: 12, padding: 12, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: Colors.border },
  statValue: { fontSize: 20, fontWeight: "700", color: Colors.text },
  statLabel: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  bzBaseBreakdownRow: { flexDirection: "row", alignItems: "center", marginTop: 4, gap: 4 },
  bzBaseBreakdownItem: { fontSize: 10, color: Colors.textSecondary },
  bzBaseBreakdownDot: { fontSize: 10, color: Colors.textSecondary },
  lastRun: { fontSize: 11, color: Colors.textSecondary, marginTop: 8, textAlign: "right" },
  lockCard: { flexDirection: "row", alignItems: "center", backgroundColor: Colors.surface, borderRadius: 12, padding: 16, gap: 14, borderWidth: 1, borderColor: Colors.border },
  lockCardStale: { borderColor: Colors.error },
  lockTitle: { fontSize: 16, fontWeight: "600", color: Colors.text },
  lockSub: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  unlockBtn: { backgroundColor: Colors.warning, width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" },
  unlockBtnStale: { backgroundColor: Colors.error },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  statusBadgeText: { fontSize: 10, fontWeight: "700" },
  okCard: { flexDirection: "row", alignItems: "center", backgroundColor: Colors.surface, borderRadius: 10, padding: 12, gap: 10, borderWidth: 1, borderColor: Colors.success + "44" },
  okText: { fontSize: 13, color: Colors.textSecondary, flex: 1 },
  issueCard: { backgroundColor: Colors.surface, borderRadius: 10, padding: 12, marginBottom: 8, borderLeftWidth: 4, borderWidth: 1, borderColor: Colors.border },
  issueCat: { fontSize: 11, fontWeight: "700", marginBottom: 2 },
  issueMsg: { fontSize: 13, color: Colors.text, lineHeight: 18 },
  embeddingTile: { flexDirection: "row", alignItems: "center", backgroundColor: Colors.surface, borderRadius: 12, padding: 16, gap: 12, borderWidth: 1, borderColor: Colors.border },
  embeddingTileWarn: { borderColor: Colors.warning + "66" },
  embeddingLabel: { fontSize: 14, color: Colors.textSecondary },
  embeddingValue: { fontSize: 18, fontWeight: "700", color: Colors.success, marginTop: 2 },
  warnBadge: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: Colors.warning + "22", paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  warnBadgeText: { fontSize: 10, fontWeight: "700", color: Colors.warning },
  musicCard: { backgroundColor: Colors.surface, borderRadius: 12, padding: 16, borderWidth: 1, borderColor: Colors.border },
  musicRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
  musicKpi: { alignItems: "center", flex: 1 },
  musicKpiValue: { fontSize: 18, fontWeight: "700", color: Colors.text },
  musicKpiLabel: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  musicLastRunBox: { backgroundColor: Colors.background, borderRadius: 8, padding: 12, marginBottom: 12 },
  musicRunRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 },
  musicRunText: { fontSize: 12, fontWeight: "600", color: Colors.textSecondary, flex: 1 },
  musicRunTimestamp: { fontSize: 11, color: Colors.textSecondary },
  musicRunKpiRow: { flexDirection: "row", justifyContent: "space-between" },
  musicRunKpi: { alignItems: "center" },
  musicRunKpiVal: { fontSize: 14, fontWeight: "700", color: Colors.text },
  musicRunKpiLbl: { fontSize: 10, color: Colors.textSecondary },
  musicHistoryBox: { borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 12 },
  musicHistoryTitle: { fontSize: 12, fontWeight: "700", color: Colors.textSecondary, marginBottom: 8 },
  musicHistoryRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 4 },
  musicHistoryTime: { fontSize: 11, color: Colors.textSecondary, width: 80 },
  musicHistoryStat: { fontSize: 11, color: Colors.textSecondary },
  linksGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  linkCard: { width: "31%", backgroundColor: Colors.surface, borderRadius: 12, padding: 16, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: Colors.border, minHeight: 90 },
  linkLabel: { fontSize: 12, fontWeight: "600", color: Colors.text, marginTop: 8, textAlign: "center" },
});
