import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  section: { marginHorizontal: 12, marginTop: 16 },
  sectionTitle: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: Colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },

  modeRow: { flexDirection: "row", gap: 8 },
  modeChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  modeChipActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  modeChipText: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.textSecondary },
  modeChipTextActive: { color: "#fff" },
  modeHint: {
    fontFamily: "Inter_400Regular",
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 8,
    lineHeight: 16,
  },
  warnCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 10,
    padding: 10,
    backgroundColor: Colors.warning + "18",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.warning + "44",
  },
  warnText: { fontFamily: "Inter_400Regular", fontSize: 11, color: Colors.text, flex: 1, lineHeight: 16 },

  monitorCard: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  monitorTopRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
  monitorStat: { alignItems: "center", flex: 1 },
  monitorValue: { fontFamily: "Inter_700Bold", fontSize: 18, color: Colors.text },
  monitorLabel: { fontFamily: "Inter_400Regular", fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  barTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.border,
    overflow: "hidden",
  },
  barFill: { height: 8, borderRadius: 4 },
  barCaption: {
    fontFamily: "Inter_400Regular",
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 6,
    textAlign: "right",
  },

  tableHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  areaCard: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 8,
  },
  areaTopRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  areaInfo: { flex: 1 },
  areaNameRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  areaName: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.text },
  tierBadge: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6 },
  tierBadgeText: { fontFamily: "Inter_600SemiBold", fontSize: 10, textTransform: "uppercase", letterSpacing: 0.3 },
  areaCountries: { fontFamily: "Inter_400Regular", fontSize: 11, color: Colors.textSecondary, marginTop: 3 },
  areaStatusCol: { alignItems: "flex-end" },
  statusDotRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  dot: { width: 9, height: 9, borderRadius: 5 },
  statusText: { fontFamily: "Inter_500Medium", fontSize: 11 },
  areaMetricsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  metricCell: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  metricText: { fontFamily: "Inter_500Medium", fontSize: 12, color: Colors.text },

  logCard: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden",
  },
  logRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  logTime: { fontFamily: "Inter_500Medium", fontSize: 11, color: Colors.textSecondary, width: 64 },
  logBody: { flex: 1 },
  logMain: { fontFamily: "Inter_500Medium", fontSize: 12, color: Colors.text },
  logReason: { fontFamily: "Inter_400Regular", fontSize: 11, color: Colors.textSecondary, marginTop: 2 },

  emptyCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  emptyText: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary, flex: 1, lineHeight: 17 },

  // Timeline cronologia up/down
  timelineIconCol: { width: 24, alignItems: "center", paddingTop: 1 },
  timelineBody: { flex: 1 },
  timelineTopRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  timelineBadge: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    borderWidth: 1,
    overflow: "hidden",
  },
  timelineArea: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: Colors.text, flex: 1 },
  timelineCode: { fontFamily: "Inter_400Regular", fontSize: 10, color: Colors.textSecondary },
  timelineBottomRow: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 2 },
  timelineLatency: { fontFamily: "Inter_400Regular", fontSize: 10, color: Colors.textSecondary },

  refreshBtn: { padding: 4 },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ghChip: {
    width: "30%",
    flexGrow: 1,
    minWidth: 90,
    maxWidth: 120,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 8,
    alignItems: "center",
  },
  ghChipHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  ghDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  ghChipStatus: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  ghChipName: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: Colors.text,
    textAlign: "center",
  },
  ghChipPort: {
    fontFamily: "Inter_400Regular",
    fontSize: 10,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  ghChipLatency: {
    fontFamily: "Inter_500Medium",
    fontSize: 10,
    marginTop: 3,
    textAlign: "center",
  },
  ghChipBuild: {
    fontFamily: "Inter_400Regular",
    fontSize: 9,
    color: Colors.textSecondary,
    marginTop: 4,
    textAlign: "center",
  },
  ghChipProfiles: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 4,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  ghChipProfilesText: {
    fontFamily: "Inter_400Regular",
    fontSize: 9,
    color: Colors.textSecondary,
    textAlign: "center",
    flexShrink: 1,
  },
});
