-- migrate:no-transaction
--
-- Migration 0095 — INTENTIONALLY A NO-OP
--
-- L'indice HNSW e l'estensione pgvector sono gestiti dalla boot sequence
-- (server/boot-sequence.ts Phase 3) ad ogni avvio, DOPO che le migration
-- sono state applicate. Questo garantisce che pgvector sia già installato
-- nel DB prima che l'indice venga creato, indipendentemente dall'ambiente.
--
-- Tentare CREATE EXTENSION + CREATE INDEX CONCURRENTLY dentro una migration
-- fallisce in produzione perché pgvector non è ancora attivo quando il runner
-- esegue le migration (il runner gira prima del boot del server).
--
-- L'indice è creato da:
--   server/boot-sequence.ts → Phase 3 → hnsw self-heal block
-- L'extension è garantita da:
--   server/boot-sequence.ts → Phase 3 → pgvector ensure block
--
-- Non rimuovere questo file: è già registrato in schema_migrations su dev.

SELECT 1;
