import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  section: {
    paddingHorizontal: 16,
    marginTop: 4,
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  settingRowTop: {
    borderTopWidth: 0,
    paddingTop: 0,
    marginBottom: 4,
  },
  settingTextCol: {
    flex: 1,
    gap: 2,
  },
  settingTitle: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  settingSubtitle: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
  },
  calibBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  calibBadgeText: {
    fontSize: 22,
    fontFamily: "Inter_500Medium",
  },
  telemetryCard: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: Colors.accent + "33",
  },
  telemetryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  telemetryTitle: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  telemetryPct: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    color: Colors.accent,
  },
  telemetryBarBg: {
    height: 6,
    backgroundColor: Colors.border,
    borderRadius: 3,
    overflow: "hidden",
  },
  telemetryBarFill: {
    height: 6,
    backgroundColor: Colors.accent,
    borderRadius: 3,
  },
  telemetryFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  telemetryKm: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    color: Colors.text,
  },
  telemetryTarget: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
  },
  telemetrySessions: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
  },
  trackKmRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  trackKmLabel: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#e67e22",
  },
  trackKmValue: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    color: "#e67e22",
  },
  telemetryExpanded: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: 12,
    gap: 10,
  },
  telemetryExpandedHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  telemetryExpandedTitle: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  telemetryResetBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#e74c3c44",
    backgroundColor: "#e74c3c11",
  },
  telemetryResetBtnText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: "#e74c3c",
  },
  savedLapsSection: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: 12,
    gap: 8,
  },
  savedLapsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  savedLapsTitle: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  compareModeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.accent,
  },
  compareModeBtnActive: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  compareModeBtnText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: Colors.accent,
  },
  compareModeBtnTextActive: {
    color: "#fff",
  },
  compareHint: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    textAlign: "center",
    paddingVertical: 4,
  },
  comparePanel: {
    backgroundColor: Colors.background,
    borderRadius: 8,
    padding: 10,
    gap: 6,
    borderWidth: 1,
    borderColor: Colors.accent + "44",
  },
  compareHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  compareHeaderCell: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    color: Colors.accent,
  },
  compareHeaderMid: {
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    color: Colors.textSecondary,
    marginHorizontal: 4,
  },
  compareHeaderRight: {
    textAlign: "right",
  },
  compareRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  compareCell: {
    flex: 1,
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  compareCellRight: {
    textAlign: "right",
  },
  compareCellWinner: {
    color: "#27ae60",
  },
  compareLabel: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    marginHorizontal: 6,
    textAlign: "center",
    minWidth: 60,
  },
  savedLapCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.background,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  savedLapCardSelected: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accent + "11",
  },
  savedLapCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  lapCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: Colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  lapCheckboxSelected: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  savedLapNum: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  savedLapDate: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    marginTop: 1,
  },
  savedLapStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  savedLapStatItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  savedLapStatVal: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  savedLapStatUnit: {
    fontSize: 9,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
  },
  savedLapSamples: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
  },
});
