import { createHash } from "crypto";
import { sql } from "drizzle-orm";
import { db, pool } from "../db";
import { embeddings } from "@shared/db";
import {
  generateEmbedding,
  getLastUsedModelTag,
  EMBEDDING_DIMENSIONS,
} from "./client";
import { storage } from "../storage";

const EF_SEARCH_DEFAULT = 64;
const EF_SEARCH_MIN = 1;
const EF_SEARCH_MAX = 1000;

/**
 * Read hnsw.ef_search from AppSetting `embedding_ef_search`.
 * Falls back to 64 if the setting is absent or invalid.
 * Result is clamped to [1, 1000] for safety.
 */
async function getEfSearch(): Promise<number> {
  try {
    const setting = await storage.getAppSetting("embedding_ef_search");
    if (!setting?.value) return EF_SEARCH_DEFAULT;
    const n = parseInt(setting.value, 10);
    if (!Number.isFinite(n)) return EF_SEARCH_DEFAULT;
    return Math.max(EF_SEARCH_MIN, Math.min(EF_SEARCH_MAX, n));
  } catch {
    return EF_SEARCH_DEFAULT;
  }
}

/**
 * Task #2514 — Embeddings store: upsert + similarity search helpers.
 *
 * Uses pgvector's cosine distance operator `<=>` and the HNSW index on
 * `embeddings.embedding` (vector_cosine_ops). Similarity is returned as
 * `1 - distance` in `[0, 1]` (clamped server-side by pgvector).
 */

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function toVectorLiteral(vec: number[]): string {
  if (vec.length !== EMBEDDING_DIMENSIONS) {
    throw new Error(
      `Vector dimension mismatch: expected ${EMBEDDING_DIMENSIONS}, got ${vec.length}`,
    );
  }
  return `[${vec.join(",")}]`;
}

export interface UpsertEmbeddingResult {
  id: string;
  cached: boolean;
  model: string;
  durationMs: number;
}

/**
 * Generate (or reuse cached) embedding for `text` and upsert it under
 * `(entityType, entityId, field)`. When the sourceHash matches the existing
 * row, no API call is made and `cached=true` is returned.
 */
export async function upsertEmbedding(
  entityType: string,
  entityId: string,
  field: string,
  text: string,
): Promise<UpsertEmbeddingResult> {
  const cleaned = text?.trim();
  if (!cleaned) {
    throw new Error("upsertEmbedding: testo vuoto");
  }
  const hash = sha256(cleaned);
  const started = Date.now();

  const existing = await db.execute<{ id: string; source_hash: string | null; model: string | null }>(
    sql`SELECT id, source_hash, model FROM embeddings
        WHERE entity_type = ${entityType}
          AND entity_id = ${entityId}
          AND field = ${field}
        LIMIT 1`,
  );
  const existingRow = (existing.rows ?? existing)[0] as
    | { id: string; source_hash: string | null; model: string | null }
    | undefined;
  if (existingRow && existingRow.source_hash === hash) {
    return {
      id: existingRow.id,
      cached: true,
      model: existingRow.model ?? "unknown",
      durationMs: Date.now() - started,
    };
  }

  const vector = await generateEmbedding(cleaned);
  const literal = toVectorLiteral(vector);
  const usedModel = getLastUsedModelTag();

  const upserted = await db.execute<{ id: string }>(
    sql`INSERT INTO embeddings
          (entity_type, entity_id, field, embedding, model, source_hash, updated_at)
        VALUES
          (${entityType}, ${entityId}, ${field}, ${literal}::vector,
           ${usedModel}, ${hash}, now())
        ON CONFLICT (entity_type, entity_id, field) DO UPDATE
          SET embedding = EXCLUDED.embedding,
              model = EXCLUDED.model,
              source_hash = EXCLUDED.source_hash,
              updated_at = now()
        RETURNING id`,
  );
  const row = (upserted.rows ?? upserted)[0] as { id: string };
  return {
    id: row.id,
    cached: false,
    model: usedModel,
    durationMs: Date.now() - started,
  };
}

export interface SimilarHit {
  id: string;
  entityType: string;
  entityId: string;
  field: string;
  similarity: number;
  model: string;
  updatedAt: Date;
}

/**
 * Find rows whose embedding is similar to `vec`, ordered by cosine distance.
 * Filters by `entityType` and `field`. Returns at most `limit` rows whose
 * similarity is >= `minSimilarity` (default 0).
 */
export async function findSimilar(
  entityType: string,
  field: string,
  vec: number[],
  limit = 5,
  minSimilarity = 0,
  /**
   * When provided, restricts the search to rows generated by the same
   * embedding model. Cross-provider cosine (e.g. openai vs local) is NOT
   * meaningful, so callers that mix providers must filter explicitly.
   */
  modelFilter?: string,
): Promise<SimilarHit[]> {
  const literal = toVectorLiteral(vec);
  const safeLimit = Math.max(1, Math.min(100, Math.floor(limit)));
  const maxDistance = 1 - Math.max(0, Math.min(1, minSimilarity));
  const efSearch = await getEfSearch();

  // Acquire a dedicated connection so that SET LOCAL (transaction-scoped) and
  // the SELECT run on the same connection without leaking the setting.
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(`SET LOCAL hnsw.ef_search = ${efSearch}`);

    const selectSql = modelFilter
      ? `SELECT id, entity_type, entity_id, field, model, updated_at,
                (embedding <=> $1::vector) AS distance
         FROM embeddings
         WHERE entity_type = $2
           AND field = $3
           AND model = $4
           AND (embedding <=> $1::vector) <= $5
         ORDER BY embedding <=> $1::vector
         LIMIT $6`
      : `SELECT id, entity_type, entity_id, field, model, updated_at,
                (embedding <=> $1::vector) AS distance
         FROM embeddings
         WHERE entity_type = $2
           AND field = $3
           AND (embedding <=> $1::vector) <= $4
         ORDER BY embedding <=> $1::vector
         LIMIT $5`;

    const params = modelFilter
      ? [literal, entityType, field, modelFilter, maxDistance, safeLimit]
      : [literal, entityType, field, maxDistance, safeLimit];

    const result = await client.query<{
      id: string;
      entity_type: string;
      entity_id: string;
      field: string;
      distance: number | string;
      model: string;
      updated_at: Date;
    }>(selectSql, params);

    await client.query("COMMIT");

    return result.rows.map((r) => ({
      id: r.id,
      entityType: r.entity_type,
      entityId: r.entity_id,
      field: r.field,
      similarity: 1 - Number(r.distance),
      model: r.model,
      updatedAt: r.updated_at,
    }));
  } catch (err) {
    await client.query("ROLLBACK").catch(() => undefined);
    throw err;
  } finally {
    client.release();
  }
}

/**
 * Delete the embedding row for `(entityType, entityId, field)` if it exists.
 * Returns the number of rows deleted (0 or 1). Used when the source text is
 * cleared by the user so that stale vectors are not kept around (privacy /
 * data-minimization) and downstream matchers immediately stop returning
 * results for that user.
 */
export async function deleteEmbedding(
  entityType: string,
  entityId: string,
  field: string,
): Promise<number> {
  const res = await db.execute(
    sql`DELETE FROM embeddings
        WHERE entity_type = ${entityType}
          AND entity_id = ${entityId}
          AND field = ${field}`,
  );
  // node-postgres reports rowCount, but some drivers return it at top-level.
  const count =
    (res as unknown as { rowCount?: number }).rowCount ??
    (Array.isArray((res as unknown as { rows?: unknown[] }).rows)
      ? ((res as unknown as { rows: unknown[] }).rows.length as number)
      : 0);
  return count ?? 0;
}

export { embeddings };
