import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  centered: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: Colors.background },
  content: { padding: 16 },
  errorText: { color: Colors.error, fontSize: 16, textAlign: "center" },
  typeBanner: { flexDirection: "row", alignItems: "center", padding: 12, borderRadius: 12, marginBottom: 16 },
  typeBannerLabel: { marginLeft: 10, fontSize: 16, fontWeight: "700" },
  statusBadge: { marginLeft: "auto", backgroundColor: Colors.surface, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  statusText: { fontSize: 12, color: Colors.textSecondary, textTransform: "uppercase", fontWeight: "600" },
  title: { fontSize: 24, fontWeight: "700", color: Colors.text, marginBottom: 16 },
  creatorRow: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  creatorAvatar: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", marginRight: 12 },
  creatorName: { fontSize: 15, fontWeight: "600" },
  createdDate: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  section: { marginBottom: 24 },
  sectionLabel: { fontSize: 13, fontWeight: "700", color: Colors.textSecondary, textTransform: "uppercase", letterSpacing: 1, marginBottom: 12 },
  descriptionText: { fontSize: 15, color: Colors.text, lineHeight: 22 },
  infoCard: { backgroundColor: Colors.surface, borderRadius: 16, padding: 16, marginBottom: 24, gap: 12 },
  infoRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  infoText: { fontSize: 14, color: Colors.text },
  participantRow: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors.border },
  participantAvatar: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center", marginRight: 12 },
  participantName: { fontSize: 15, color: Colors.text, fontWeight: "500" },
  creatorBadge: { marginLeft: 8 },
  joinButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: Colors.accent, paddingVertical: 14, borderRadius: 12, gap: 8, marginTop: 8 },
  joinButtonDisabled: { opacity: 0.6 },
  joinText: { fontSize: 16, fontWeight: "700", color: "#000" },
  joinedBanner: { flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: Colors.surface, paddingVertical: 12, borderRadius: 12, gap: 8, marginBottom: 12, borderWidth: 1, borderColor: Colors.border },
  joinedText: { fontSize: 15, fontWeight: "600", color: Colors.text },
  deleteButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: Colors.error, paddingVertical: 14, borderRadius: 12, gap: 8, marginTop: 12 },
  deleteButtonText: { fontSize: 15, fontWeight: "700", color: "#fff" },
  groupChatButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: Colors.text, paddingVertical: 14, borderRadius: 12, gap: 8, marginTop: 12 },
  groupChatText: { fontSize: 15, fontWeight: "700", color: Colors.background },
});
