import React from "react";
import { StyleSheet } from "react-native";

export const useGiriCreateStyles = (colors: any) => {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    nav: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12, paddingBottom: 10 },
    backBtn: { width: 40, height: 40, justifyContent: "center" },
    navTitle: { fontFamily: "Inter_700Bold", fontSize: 16, color: colors.text },
    modeRow: { flexDirection: "row", gap: 8, marginBottom: 20 },
    modeChip: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: colors.surface },
    modeChipText: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: colors.text },
    section: { marginBottom: 20 },
    sectionLabel: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: colors.textSecondary, marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 },
    aiInput: { backgroundColor: colors.surface, borderRadius: 12, padding: 14, fontFamily: "Inter_400Regular", fontSize: 15, color: colors.text, minHeight: 100, borderWidth: 1, borderColor: colors.border, marginBottom: 12 },
    primaryBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: colors.accent, borderRadius: 14, paddingVertical: 14, marginBottom: 10 },
    primaryBtnText: { fontFamily: "Inter_700Bold", fontSize: 15, color: "#000" },
    secondaryBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, borderRadius: 14, paddingVertical: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.border },
    secondaryBtnText: { fontFamily: "Inter_500Medium", fontSize: 14, color: colors.textSecondary },
    hint: { fontFamily: "Inter_400Regular", fontSize: 12, color: colors.textSecondary, textAlign: "center" },
    aiFallbackBanner: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#fef3c7", borderRadius: 10, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: "#fcd34d" },
    aiFallbackBannerText: { flex: 1, fontFamily: "Inter_400Regular", fontSize: 13, color: "#b45309" },
    aiSuccessBanner: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#dcfce7", borderRadius: 10, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: "#86efac" },
    aiSuccessBannerText: { flex: 1, fontFamily: "Inter_500Medium", fontSize: 13, color: "#15803d" },
    previewHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 },
    previewHeaderText: { fontFamily: "Inter_700Bold", fontSize: 16, color: colors.text },
    previewHint: { fontFamily: "Inter_400Regular", fontSize: 13, color: colors.textSecondary, marginBottom: 16 },
    pillSection: { marginBottom: 16 },
    pillLabel: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: colors.textSecondary, marginBottom: 6, letterSpacing: 0.5 },
    pill: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.surface, borderRadius: 12, padding: 12, borderWidth: 1 },
    pillInput: { flex: 1, fontFamily: "Inter_500Medium", fontSize: 14, color: colors.text },
    pillRow: { flexDirection: "row", gap: 8 },
    stylePill: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: colors.surface, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: colors.border },
    stylePillText: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.textSecondary },
    locationPillRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
    locationPillDot: { width: 10, height: 10, borderRadius: 5 },
    locationPill: { flex: 1, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.surface, borderRadius: 12, padding: 10, borderWidth: 1, borderColor: colors.border },
    locationPillRole: { fontFamily: "Inter_700Bold", fontSize: 11 },
    locationPillInput: { flex: 1, fontFamily: "Inter_400Regular", fontSize: 14, color: colors.text },
    optionPillRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
    optionPill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
    optionPillText: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.textSecondary },
    previewWarning: { flexDirection: "row", alignItems: "flex-start", gap: 8, backgroundColor: "#f59e0b22", borderRadius: 10, padding: 10, marginBottom: 12, borderWidth: 1, borderColor: "#f59e0b44" },
    previewWarningText: { fontFamily: "Inter_400Regular", fontSize: 12, color: "#f59e0b", flex: 1 },
    curvinessRow: { flexDirection: "row", gap: 6, marginBottom: 8 },
    curvinessBtn: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 10, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
    curvinessBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: colors.textSecondary },
    curvinessDesc: { fontFamily: "Inter_400Regular", fontSize: 12, color: colors.textSecondary, textAlign: "center" },
    profileCard: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderRadius: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, marginBottom: 8 },
    profileCardLeft: { width: 32, alignItems: "center" },
    profileCardTitle: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: colors.text, marginBottom: 2 },
    profileCardDesc: { fontFamily: "Inter_400Regular", fontSize: 12, color: colors.textSecondary },
    profileLockRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 4 },
    profileLockText: { fontFamily: "Inter_400Regular", fontSize: 11, color: colors.textSecondary },
    plannerMapContainer: { height: 220, borderRadius: 14, overflow: "hidden", position: "relative", borderWidth: 1, borderColor: colors.border },
    plannerMap: { flex: 1 },
    mapHintBadge: { position: "absolute", bottom: 8, left: "50%", transform: [{ translateX: -70 }], backgroundColor: "rgba(0,0,0,0.7)", borderRadius: 20, flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 10, paddingVertical: 5 },
    mapHintText: { fontFamily: "Inter_400Regular", fontSize: 11, color: "#fff" },
    input: { backgroundColor: colors.surface, borderRadius: 10, padding: 12, fontFamily: "Inter_400Regular", fontSize: 14, color: colors.text, borderWidth: 1, borderColor: colors.border, marginBottom: 6 },
    wpRow: { flexDirection: "row", alignItems: "flex-start", gap: 8, marginBottom: 4 },
    wpDot: { width: 20, alignItems: "center", paddingTop: 14 },
    wpDotInner: { width: 10, height: 10, borderRadius: 5 },
    addWpBtn: { flexDirection: "row", alignItems: "center", gap: 6, paddingVertical: 8 },
    addWpText: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.accent },
    suggestions: { backgroundColor: colors.surface, borderRadius: 10, borderWidth: 1, borderColor: colors.border, overflow: "hidden", marginTop: -4, marginBottom: 6 },
    suggestion: { flexDirection: "row", alignItems: "center", gap: 8, padding: 10, borderBottomWidth: 1, borderBottomColor: colors.border },
    suggestionText: { fontFamily: "Inter_400Regular", fontSize: 13, color: colors.text, flex: 1 },
    toggleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
    toggleInfo: { flexDirection: "row", alignItems: "center", gap: 10 },
    toggleLabel: { fontFamily: "Inter_500Medium", fontSize: 14, color: colors.text },
    sliderSection: { paddingHorizontal: 4, paddingTop: 8, paddingBottom: 4 },
    sliderLabelRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 4 },
    sliderLabel: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.textSecondary },
    sliderValue: { fontFamily: "Inter_700Bold", fontSize: 13, color: colors.text },
    sliderTicks: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 2 },
    sliderTick: { fontFamily: "Inter_400Regular", fontSize: 11, color: colors.textSecondary },
    compassGrid: { gap: 8 },
    compassRing: { flexDirection: "row", flexWrap: "wrap", gap: 6, justifyContent: "center" },
    compassDir: { width: 48, height: 36, borderRadius: 8, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
    compassCenter: { alignSelf: "center", paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
    compassDirText: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: colors.text },
    motoChip: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, marginRight: 8 },
    motoChipText: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.textSecondary },
    resultCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, marginTop: 16, marginBottom: 8, gap: 12 },
    resultTitle: { fontFamily: "Inter_700Bold", fontSize: 16, color: colors.text },
    resultStats: { flexDirection: "row", justifyContent: "space-around" },
    resultStat: { alignItems: "center", gap: 4 },
    resultStatValue: { fontFamily: "Inter_700Bold", fontSize: 18, color: colors.text },
    resultStatLabel: { fontFamily: "Inter_400Regular", fontSize: 12, color: colors.textSecondary },
    bikerScoreSection: { gap: 6 },
    bsLabelRow: { flexDirection: "row", justifyContent: "space-between" },
    bsLabel: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.textSecondary },
    bsValue: { fontFamily: "Inter_700Bold", fontSize: 13, color: colors.text },
    bsBarBg: { height: 8, backgroundColor: colors.border, borderRadius: 4, overflow: "hidden" },
    bsBarFill: { height: "100%", borderRadius: 4 },
    bsDesc: { fontFamily: "Inter_400Regular", fontSize: 12, color: colors.textSecondary },
    weatherBanner: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: colors.background, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: colors.border },
    weatherBannerText: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.text },
    multiDayPreview: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#7c3aed18", borderRadius: 10, padding: 10 },
    multiDayPreviewText: { fontFamily: "Inter_500Medium", fontSize: 13, color: "#a78bfa", flex: 1 },
    fuelPreview: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.accent + "18", borderRadius: 10, padding: 10 },
    fuelPreviewText: { fontFamily: "Inter_500Medium", fontSize: 13, color: colors.accent, flex: 1 },
    saveBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: colors.surface, borderRadius: 14, paddingVertical: 14, borderWidth: 1.5, borderColor: colors.accent, marginTop: 4 },
    saveBtnText: { fontFamily: "Inter_700Bold", fontSize: 15, color: colors.accent },
    approxBanner: { position: "absolute", top: 10, left: "50%", transform: [{ translateX: -90 }], flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "rgba(0,0,0,0.75)", borderRadius: 16, paddingHorizontal: 10, paddingVertical: 5, borderWidth: 1, borderColor: "#f9731650" },
    approxBannerText: { fontFamily: "Inter_500Medium", fontSize: 11, color: "#f97316" },
    calcSpinnerBadge: { position: "absolute", top: 10, right: 10, width: 32, height: 32, borderRadius: 16, backgroundColor: "rgba(0,0,0,0.65)", alignItems: "center", justifyContent: "center" },
  });
};
