import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  title: { fontSize: 17, fontWeight: "700" },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  syncBtn: { borderRadius: 6, borderWidth: 1.5, paddingHorizontal: 10, paddingVertical: 6 },
  syncBtnText: { fontSize: 12, fontWeight: "700" as const },
  listBtn: { borderRadius: 6, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 },
  listBtnText: { fontSize: 12, fontWeight: "600" as const },
  numBadge: { borderRadius: 4, paddingHorizontal: 7, paddingVertical: 3, marginRight: 4 },
  numBadgeText: { fontSize: 11, fontWeight: "800" as const, color: "#fff", letterSpacing: 0.3 },
  badgeRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", flex: 1, gap: 4 },
  warningBox: { borderRadius: 6, borderWidth: 1, padding: 10, marginTop: 8, marginBottom: 4 },
  warningText: { fontSize: 12, lineHeight: 17 },
  emptyBox: { borderRadius: 8, padding: 20, alignItems: "center", borderWidth: 1, marginBottom: 12 },
  emptyText: { fontSize: 14, fontWeight: "600", marginBottom: 4 },
  emptySubtext: { fontSize: 11, fontFamily: Platform.OS === "ios" ? "Courier" : "monospace", textAlign: "center" },
  card: { borderRadius: 8, padding: 16, marginBottom: 12, borderWidth: 1 },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  badge: { borderRadius: 4, paddingHorizontal: 8, paddingVertical: 3 },
  badgeText: { fontSize: 10, fontWeight: "800" as const, letterSpacing: 0.5 },
  dateText: { fontSize: 11 },
  versionText: {
    fontSize: 16,
    fontWeight: "700" as const,
    marginBottom: 4,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
  },
  messageText: { fontSize: 13, marginBottom: 8, lineHeight: 18 },
  metaText: {
    fontSize: 11,
    marginBottom: 2,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
  },
  actions: { flexDirection: "column", gap: 8, marginTop: 12 },
  actionBtn: { borderRadius: 6, paddingVertical: 10, paddingHorizontal: 16, alignItems: "center", borderWidth: 1 },
  actionBtnText: { fontSize: 13, fontWeight: "700" as const },
  rollbackBtn: { marginTop: 10, borderRadius: 6, paddingVertical: 8, paddingHorizontal: 12, alignItems: "center", borderWidth: 1, borderStyle: "dashed" as const },
  rollbackBtnText: { fontSize: 12, fontWeight: "600" as const },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "700" as const,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 12,
    marginTop: 8,
  },
  forceUpdateBtn: {
    borderRadius: 8,
    paddingVertical: 13,
    paddingHorizontal: 16,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginBottom: 12,
    minHeight: 46,
  },
  forceUpdateText: { color: "#fff", fontSize: 14, fontWeight: "700" as const },
  infoBanner: {
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
    marginBottom: 12,
  },
  infoBannerText: { fontSize: 12, lineHeight: 17 },
  countersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
    marginBottom: 4,
  },
  counterChip: {
    flexGrow: 1,
    minWidth: 70,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
    alignItems: "center",
  },
  counterLabel: { fontSize: 10, fontWeight: "600" as const, letterSpacing: 0.3, textTransform: "uppercase" },
  counterValue: { fontSize: 16, fontWeight: "700" as const, marginTop: 2 },
  autoRollbackBox: {
    borderRadius: 6,
    borderWidth: 1,
    padding: 10,
    marginTop: 10,
  },
  autoRollbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  autoRollbackTitle: { fontSize: 13, fontWeight: "700" as const },
  autoRollbackHint: { fontSize: 11, marginTop: 2, lineHeight: 15 },
  expandToggle: { marginTop: 8 },
  expandToggleText: { fontSize: 12, fontWeight: "600" as const },
  autoRollbackFields: { marginTop: 8, gap: 6 },
  autoFieldRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  autoFieldLabel: { fontSize: 12, flex: 1 },
  autoFieldInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 80,
  },
  autoFieldInput: { fontSize: 13, padding: 0, minWidth: 40, textAlign: "right" },
  autoFieldSuffix: { fontSize: 11, marginLeft: 4 },
  obsoleteRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 6, borderWidth: 1, marginBottom: 4 },
});
