import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const trackingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  activeHeader: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  pauseBtn: {
    flex: 1,
    height: 44,
    backgroundColor: Colors.warning,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pauseBtnResume: {
    backgroundColor: Colors.success,
  },
  pauseBtnLabel: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: "#1a1a1a",
  },
  stopBtn: {
    flex: 1,
    height: 44,
    backgroundColor: Colors.accentRed,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  stopBtnLabel: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: "#ffffff",
  },
  gpsBanner: {
    backgroundColor: Colors.accentRed,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    gap: 8,
  },
  gpsBannerText: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  gpsAcquiringBanner: {
    backgroundColor: Colors.accent,
  },
  fusionChipRow: {
    flexDirection: "row",
    justifyContent: "center",
    paddingTop: 8,
  },
  fusionChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  fusionChipSensors: {
    backgroundColor: Colors.warning,
  },
  fusionChipAcquiring: {
    backgroundColor: Colors.accent,
  },
  fusionChipText: {
    color: "#fff",
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
  },
  activeScroll: {
    padding: 16,
    gap: 16,
  },
  speedPanel: {
    backgroundColor: Colors.surface,
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.border,
  },
  speedMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 8,
  },
  fermoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  fermoDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  fermoLabel: {
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    letterSpacing: 1,
  },
  accuracyRow: {
    alignItems: "flex-end",
  },
  accuracyLabel: {
    fontSize: 10,
    fontFamily: "Inter_700Bold",
  },
  accuracyValue: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  speedValue: {
    fontSize: 84,
    fontFamily: "Inter_700Bold",
    color: Colors.accent,
    lineHeight: 90,
  },
  speedValueSprint: {
    fontSize: 64,
    lineHeight: 70,
  },
  speedUnit: {
    fontSize: 18,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
    marginTop: -8,
  },
  mapCard: {
    height: 180,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.border,
  },
  statsRow: {
    flexDirection: "row",
    gap: 12,
  },
  statsCol: {
    flex: 1,
    gap: 12,
  },
  statCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    minHeight: 80,
    justifyContent: "center",
  },
  statValue: {
    fontSize: 18,
    fontFamily: "Inter_700Bold",
    color: Colors.text,
    marginTop: 4,
  },
  statLabel: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
    textTransform: "uppercase",
    marginTop: 2,
  },
  recalibrateLink: {
    fontSize: 10,
    color: Colors.accent,
    textDecorationLine: "underline",
    marginTop: 4,
  },
  bufferRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 8,
    opacity: 0.6,
  },
  bufferText: {
    fontSize: 11,
    color: Colors.textSecondary,
    fontFamily: "Inter_400Regular",
  },
  sprintContainer: {
    gap: 16,
  },
  sprintHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sprintHeaderLabel: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: Colors.text,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  sprintHistoryBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  sprintHistoryBtnText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.accent,
  },
  sprintPhaseBadge: {
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
  },
  sprintPhaseLabel: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  sprintCancelBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 10,
  },
  sprintCancelText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: Colors.accentRed,
  },
  sprint0100Time: {
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    color: Colors.text,
    textAlign: "center",
  },
  newRecordBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FFD70020",
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#FFD70040",
  },
  newRecordText: {
    color: "#FFD700",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  sensorOverlayToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 12,
  },
  sensorOverlayToggleLabel: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  sensorOverlayToggleHint: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    marginTop: 1,
  },
  mapModalSpeed: {
    position: "absolute",
    bottom: 48,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  mapModalSpeedValue: {
    fontSize: 72,
    fontFamily: "Inter_700Bold",
    color: Colors.accent,
    lineHeight: 80,
    letterSpacing: -2,
  },
  mapModalSpeedUnit: {
    fontSize: 18,
    fontFamily: "Inter_600SemiBold",
    color: Colors.accent,
    marginTop: -4,
  },
  bgToast: {
    position: "absolute",
    left: 20,
    right: 20,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.accent + "40",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 100,
  },
  bgToastText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: Colors.text,
  },
  recordsSection: {
    marginTop: 10,
    gap: 10,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: Colors.text,
    marginBottom: 4,
    marginLeft: 4,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  emptyText: {
    textAlign: "center",
    color: Colors.textSecondary,
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    marginTop: 20,
    marginBottom: 40,
  },
});
