import type React from "react";
import type { InteractiveMapHandle, ClubMapPin } from "@/components/InteractiveMap";

export type FullscreenMapModalProps = {
  visible: boolean;
  onClose: () => void;
  mapRef: React.RefObject<InteractiveMapHandle | null>;
  users: any[];
  workshops: any[];
  easterEggs: any[];
  activeSosRequests: any[];
  isAvailable: boolean;
  ghostMode: boolean;
  searchRadiusKm: number;
  filterBiker: boolean;
  filterZavorrina: boolean;
  filterClubs: boolean;
  filterEvents: boolean;
  onToggleFilterBiker: () => void;
  onToggleFilterZavorrina: () => void;
  onToggleFilterClubs: () => void;
  onToggleFilterEvents: () => void;
  onUserPress: (u: any) => void;
  onEasterEggPress: (egg: any) => void;
  onEventPress: (id: string) => void;
  onClubPress: (club: any) => void;
  onProposeClubLocation: (club: any) => void;
  currentUserId: string | null | undefined;
  realMeMarker: { latitude: number; longitude: number } | null;
  fakeMeMarker: { latitude: number; longitude: number } | null;
  clubPins: ClubMapPin[];
  initialCenterOverride: { latitude: number; longitude: number } | null;
  filterBarTopOffset: number;
  onShowAreaModal: () => void;
  areaLabel: string;
  onRegionChangeComplete?: (center: { latitude: number; longitude: number }) => void;
  onMapReady?: () => void;
  searchText: string;
  onSearch: (text: string) => void;
  onClearSearch: () => void;
  searchResults: any[];
  searchLoading: boolean;
  showSearchResults: boolean;
  onSearchResultPress: (u: any) => void;
  currentUserFullId: string | null | undefined;
  onlineCount: number;
  bikerCount: number;
  zavCount: number;
  insetsTop: number;
  insetsBottom: number;
  isReady: boolean;
  getUserIcon: (u: any) => any;
  getUserColor: (u: any) => string;
  getUserTypeLabel: (u: any) => string;
};
