import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  loading: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: Colors.background },
  loadingText: { color: Colors.textSecondary, marginTop: 12, fontFamily: "Inter_400Regular" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  titleRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: 8 },
  title: { fontSize: 24, fontFamily: "Inter_700Bold", color: Colors.accent },
  helmetLogo: { width: 32, height: 32, tintColor: Colors.accent },
  searchContainer: { marginHorizontal: 16, marginBottom: 8, zIndex: 10 },
  searchInputRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: Colors.surface,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  searchInput: { flex: 1, fontSize: 14, fontFamily: "Inter_400Regular", color: Colors.text, padding: 0 },
  searchResultsContainer: {
    backgroundColor: Colors.surface,
    borderRadius: 10,
    marginTop: 4,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden" as const,
  },
  searchNoResults: { padding: 12, textAlign: "center" as const, color: Colors.textSecondary, fontSize: 13, fontFamily: "Inter_400Regular" },
  searchResultItem: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.border,
  },
  searchResultName: { fontSize: 14, fontFamily: "Inter_600SemiBold", color: Colors.text },
  searchResultDetail: { fontSize: 12, fontFamily: "Inter_400Regular", color: Colors.textSecondary, marginTop: 1 },
  mapContainer: {
    height: 253,
    marginHorizontal: 16,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
  },
  mapPlaceholder: { flex: 1, backgroundColor: Colors.background, alignItems: "center", justifyContent: "center" },
  expandHint: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: Colors.surface + "CC",
    borderRadius: 8,
    padding: 6,
  },
  statsRow: { flexDirection: "row", paddingHorizontal: 16, gap: 8, marginTop: 8 },
  statCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
    alignItems: "center",
    gap: 2,
  },
  statTopRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: 6 },
  statNumber: { fontSize: 22, fontFamily: "Inter_700Bold", color: Colors.text },
  statLabel: { fontSize: 9, fontFamily: "Inter_400Regular", color: Colors.textSecondary, textAlign: "center" as const, lineHeight: 12 },
  defineAreaBtnInline: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: Colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.accent + "30",
    maxWidth: 140,
  },
  defineAreaBtnInlineText: { fontSize: 12, fontFamily: "Inter_500Medium", color: Colors.accent, flexShrink: 1 },
  locationNudge: {
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: "#1C1A12",
    borderWidth: 1,
    borderColor: "#F59E0B44",
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  locationNudgeContent: { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 8 },
  locationNudgeText: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular", color: Colors.text, lineHeight: 18 },
  locationNudgeActions: { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "flex-end" as const, gap: 8 },
  locationNudgeHowBtn: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, backgroundColor: "#F59E0B22" },
  locationNudgeHowText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: "#F59E0B" },
  locationNudgeDismissBtn: { padding: 4 },
});

export default styles;
