import type { AdminGroup } from "@/components/admin/admin-types";

export const adminGroupsPart1: AdminGroup[] = [
  {
    title: "Utenti",
    headerIcon: "people",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "users",
        label: "Utenti",
        icon: "people",
        iconSet: "MaterialIcons",
        route: "/admin/users",
        keywords: ["utente", "user", "account", "profilo", "profile", "ban", "sospendi", "sospensione", "blocca", "block", "registrazione", "lista utenti", "elimina utente", "delete user", "verifica email", "email verification", "ruolo", "role", "modifica utente", "cerca utente", "search user"],
      },
      {
        key: "stregatti",
        label: "Stregatti",
        icon: "robot",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/stregatti",
        keywords: ["stregatto", "bot", "robot", "fake", "simulato", "utente finto", "seed", "automatico", "automated", "simulazione", "phantom", "dummy", "account finto", "test user", "utente test"],
      },
      {
        key: "blocks",
        label: "Blocchi",
        icon: "ban",
        iconSet: "Ionicons",
        route: "/admin/blocks",
        keywords: ["blocco", "block", "ban", "sospensione", "bannato", "banned", "sospeso", "mute", "silenzia", "restrizione", "restriction", "kick", "rimuovi", "sanzione", "penalty"],
      },
    ],
  },
  {
    title: "Report",
    headerIcon: "flag-variant",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "reports-hub",
        label: "Hub Report",
        icon: "view-dashboard-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-hub",
        accentColor: "#FF3B30",
        keywords: ["segnalazione", "report", "hub", "dashboard", "reclamo", "abuso", "overview", "riepilogo", "violazione", "violation", "contenuto inappropriato", "moderazione"],
      },
      {
        key: "reports",
        label: "Coda Segnalazioni",
        icon: "flag",
        iconSet: "MaterialIcons",
        route: "/admin/reports",
        accentColor: "#FF9500",
        keywords: ["segnalazione", "report", "coda", "queue", "flag", "revisione", "moderazione", "pending", "in attesa", "spam", "contenuto inappropriato", "inappropriate", "review", "approva", "rifiuta", "reject"],
      },
      {
        key: "reports-by-category",
        label: "Per Categoria",
        icon: "shape-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-by-category",
        accentColor: "#0EA5E9",
        keywords: ["segnalazione", "report", "categoria", "category", "tipo", "type", "filtro", "filter", "classificazione", "classification", "raggruppamento", "group", "odio", "hate", "violenza", "violence", "nudità", "nudity"],
      },
      {
        key: "reports-by-role",
        label: "Per Ruolo",
        icon: "account-group-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-by-role",
        accentColor: "#10B981",
        keywords: ["segnalazione", "report", "ruolo", "role", "moderatore", "admin", "assegnazione", "assignment", "responsabile", "owner", "gestione", "management", "chi gestisce"],
      },
      {
        key: "reports-patterns",
        label: "Pattern",
        icon: "chart-bell-curve",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-patterns",
        accentColor: "#E91E63",
        keywords: ["pattern", "analisi", "trend", "grafico", "chart", "segnalazione ricorrente", "frequenza", "frequency", "ripetuto", "repeated", "utente problematico", "serie temporale", "picco", "spike"],
      },
      {
        key: "false-reports",
        label: "Falsi Report",
        icon: "shield-alert-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/false-reports",
        accentColor: "#9C27B0",
        keywords: ["falso", "false", "spam", "abuso segnalazione", "false report", "report errato", "trolling", "in malafede", "sanzione", "penalty", "segnalazione abusiva", "bad faith"],
      },
      {
        key: "active-bans",
        label: "Ban Attivi",
        icon: "account-cancel-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/active-bans",
        accentColor: "#FF3B30",
        keywords: ["ban", "bannato", "sospeso", "sospensione", "blocco", "attivo", "active", "scadenza", "expiry", "durata", "duration", "temporaneo", "temporary", "permanente", "permanent", "sanzione", "rimuovi ban"],
      },
      {
        key: "moderator-logs",
        label: "Log Moderatori",
        icon: "shield-account-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/moderator-logs",
        accentColor: "#6366F1",
        keywords: ["log", "moderatore", "moderazione", "storico", "history", "audit", "azioni admin", "audit trail", "registro", "chi ha fatto cosa", "admin actions", "operazioni", "traccia moderazione"],
      },
      {
        key: "reports-thresholds",
        label: "Soglie & Policy",
        icon: "tune-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/reports-thresholds",
        accentColor: "#22C55E",
        keywords: ["soglia", "threshold", "policy", "regola", "rule", "limite", "limit", "configurazione moderazione", "automatico", "auto-ban", "trigger", "impostazione", "auto-moderation", "parametri"],
      },
    ],
  },
  {
    title: "Contenuti",
    headerIcon: "layers",
    headerIconSet: "MaterialIcons",
    items: [
      {
        key: "workshops",
        label: "Officine",
        icon: "store",
        iconSet: "MaterialIcons",
        route: "/admin/workshops",
        keywords: ["officina", "workshop", "meccanico", "negozio", "shop", "riparazione", "garage", "partner", "servizio", "service", "verificato", "verified", "moto", "motorcycle", "gommista", "carrozzeria"],
      },
      {
        key: "motoclubs",
        label: "Clubs",
        icon: "shield",
        iconSet: "Ionicons",
        route: "/admin/motoclubs",
        keywords: ["club", "motoclub", "gruppo", "community", "associazione", "gang", "biker", "organizzazione", "organization", "admin club", "gestione club", "modifica club", "approva club", "membro"],
      },
      {
        key: "eventi",
        label: "Raduni",
        icon: "calendar",
        iconSet: "Ionicons",
        route: "/admin/eventi",
        keywords: ["evento", "event", "raduno", "meeting", "incontro", "calendario", "gita", "uscita", "approvazione", "approval", "cancella", "cancel", "partecipanti", "participants", "iscrizioni", "date", "data"],
      },
      {
        key: "easter-eggs",
        label: "Easter Eggs",
        icon: "egg-easter",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/easter-eggs",
        keywords: ["easter egg", "segreto", "hidden", "nascosto", "badge", "achievement", "premi", "gamification", "ricompensa", "reward", "sblocca", "unlock", "missione", "mission", "livello", "level"],
      },
      {
        key: "ads",
        label: "Campagne",
        icon: "campaign",
        iconSet: "MaterialIcons",
        route: "/admin/ads",
        keywords: ["campagna", "ads", "pubblicità", "advertising", "banner", "promozione", "sponsor", "monetizzazione", "monetization", "impressioni", "impressions", "click", "ctr", "budget", "targeting", "annuncio", "annunci"],
      },
    ],
  },
  {
    title: "Monitoraggio",
    headerIcon: "bar-chart",
    headerIconSet: "Ionicons",
    items: [
      {
        key: "analytics",
        label: "Analytics",
        icon: "analytics",
        iconSet: "MaterialIcons",
        route: "/admin/analytics",
        keywords: ["analytics", "statistiche", "stats", "metriche", "dati", "grafico", "chart", "kpi", "utenti attivi", "active users", "retention", "crescita", "growth", "dashboard", "andamento", "report analytics"],
      },
      {
        key: "performance",
        label: "Performance",
        icon: "speedometer",
        iconSet: "Ionicons",
        route: "/admin/performance",
        keywords: ["performance", "prestazioni", "velocità", "speed", "latenza", "latency", "benchmark", "tempo risposta", "response time", "throughput", "server load", "ottimizzazione", "optimization", "api response", "slow"],
      },
      {
        key: "gps-errors",
        label: "GPS Error Log",
        icon: "location-sharp",
        iconSet: "Ionicons",
        route: "/admin/gps-errors",
        keywords: ["gps", "errore", "error", "log", "posizione", "location", "geolocalizzazione", "timeout", "segnale", "signal", "accuratezza", "accuracy", "coordinate", "satellite", "gnss", "fix gps"],
      },
      {
        key: "gps-rejections",
        label: "GPS Rifiutati",
        icon: "alert-circle",
        iconSet: "Ionicons",
        route: "/admin/gps-rejections",
        accentColor: "#FF9500",
        keywords: ["gps", "rifiutato", "rejected", "scartato", "posizione scartata", "filtro gps", "outlier", "anomalo", "anomaly", "spike", "jitter", "coordinate errate", "invalid position", "salto gps"],
      },
      {
        key: "db-debug",
        label: "DB Debug",
        icon: "database",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/db-debug",
        keywords: ["database", "db", "debug", "sql", "query", "postgres", "tabella", "schema", "indice", "index", "slow query", "explain", "piano esecuzione", "ottimizzazione query", "performance db", "postgresql"],
      },
      {
        key: "db-tables",
        label: "Dimensioni DB",
        icon: "database-settings",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/db-tables",
        keywords: ["database", "db", "dimensione", "size", "spazio", "storage", "tabella", "peso", "ottimizzazione", "vacuum", "pulizia", "cleanup", "occupazione", "bloat", "gigabyte", "mb"],
      },
      {
        key: "system",
        label: "System Monitor",
        icon: "pulse-outline",
        iconSet: "Ionicons",
        route: "/admin/system",
        accentColor: "#FF4444",
        keywords: ["sistema", "system", "monitor", "cpu", "ram", "memoria", "server", "risorse", "health", "load average", "disco", "disk", "io", "rete", "network", "uptime", "availability", "processo", "process"],
      },
      {
        key: "resource-monitor",
        label: "Risorse & Salute",
        icon: "memory",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/resource-monitor",
        accentColor: "#8B5CF6",
        keywords: ["risorse", "salute", "resource", "ram", "batteria", "battery", "crash", "riavvio", "restart", "grafico", "campionamento", "metriche dispositivo", "uptime", "logging weight", "memoria", "cpu", "health"],
      },
      {
        key: "db-monitor",
        label: "Database Monitor",
        icon: "database-clock",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/db-monitor",
        accentColor: "#8B5CF6",
        keywords: ["database", "db", "monitor", "carico", "load", "overload", "sovraccarico", "pool", "saturazione", "ping", "latenza", "latency", "backend", "cpu", "event loop", "event-loop", "storico", "history", "trend", "30 giorni", "download", "csv", "restart", "errori", "produzione", "postgres"],
      },
      {
        key: "moderator-logs",
        label: "Log Moderatori",
        icon: "shield-account-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/moderator-logs",
        keywords: ["log", "moderatore", "moderazione", "storico", "history", "audit", "azioni admin", "audit trail", "registro", "chi ha fatto cosa", "admin actions", "operazioni", "traccia"],
      },
      {
        key: "crash-logs",
        label: "Log Riavvii",
        icon: "phone-alert",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/crash-logs",
        accentColor: "#FF6B35",
        keywords: ["crash", "riavvio", "restart", "log", "errore app", "crash report", "stability", "eccezione", "exception", "stack trace", "traceback", "fatal", "oom", "out of memory", "freeze", "hang", "errore critico"],
      },
      {
        key: "visitatori",
        label: "Visitatori Sito",
        icon: "web",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/visitatori",
        accentColor: "#22C55E",
        keywords: ["visitatore", "visitor", "sito", "web", "landing", "traffico", "traffic", "accessi", "sessione web", "bounce rate", "conversione", "conversion", "funnel", "registrati", "nuovo utente"],
      },
      {
        key: "device-stats",
        label: "Dispositivi",
        icon: "cellphone-check",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/device-stats",
        accentColor: "#6366F1",
        keywords: ["dispositivo", "device", "telefono", "phone", "ios", "android", "versione app", "client", "sistema operativo", "os version", "modello", "model", "distribuzione", "app version", "screen", "schermo"],
      },
      {
        key: "push-diagnostics",
        label: "Diagnostica Push",
        icon: "bell-alert",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/push-diagnostics",
        accentColor: "#EF4444",
        keywords: ["notifica", "notifiche", "push", "push notification", "token", "expo push token", "fcm", "apns", "permessi negati", "permission denied", "perché non ricevo notifiche", "mancato token", "copertura push", "delivery", "avviso"],
      },
    ],
  },
  {
    title: "Marketing",
    headerIcon: "email-newsletter",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "marketing",
        label: "Business Reach",
        icon: "storefront",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/marketing",
        accentColor: "#AD1457",
        keywords: ["business", "locale", "locali", "concessionaria", "concessionarie", "reach", "marketing", "passaggi", "passaggi qualificati", "conversioni", "click", "report mensile", "attiva", "disattiva", "toggle", "raggio", "radius", "marker", "mappa business", "partner commerciale", "inserzionista"],
      },
      {
        key: "newsletter",
        label: "Newsletter",
        icon: "email-newsletter",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/newsletter",
        accentColor: "#2196F3",
        keywords: ["newsletter", "email", "mailing", "iscritti", "subscriber", "invio", "comunicazione", "campagna email", "template", "invio massivo", "mass mail", "open rate", "apertura", "disiscritto", "unsubscribe", "notifica email"],
      },
    ],
  },
  {
    title: "Matching",
    headerIcon: "link-variant",
    headerIconSet: "MaterialCommunityIcons",
    items: [
      {
        key: "matching-hub",
        label: "Hub Matching",
        icon: "view-dashboard-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/matching-hub",
        accentColor: "#0EA5E9",
        keywords: ["matching", "hub", "dashboard", "accoppiamento", "suggerimenti", "recommendations", "overview", "panoramica", "riepilogo matching", "statistiche match"],
      },
      {
        key: "match-engine",
        label: "Motore Matching",
        icon: "engine",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-engine",
        accentColor: "#FF9500",
        keywords: ["matching", "motore", "engine", "algoritmo", "algorithm", "ml", "intelligenza artificiale", "ai matching", "score", "punteggio", "compatibilità", "compatibility", "configurazione motore"],
      },
      {
        key: "match-rules",
        label: "Regole Matching",
        icon: "table-large",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-rules",
        accentColor: "#10B981",
        keywords: ["matching", "regola", "rule", "configurazione", "peso", "score", "criterio", "parametro", "priorità", "priority", "filtro", "filter", "condizione"],
      },
      {
        key: "match-inspector",
        label: "Match Inspector",
        icon: "account-search",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-inspector",
        accentColor: "#2196F3",
        keywords: ["matching", "inspector", "ispezione", "debug match", "coppia", "pair", "analisi match", "perché match", "why matched", "dettaglio", "detail", "spiegazione", "explanation"],
      },
      {
        key: "match-control",
        label: "Controllo Sistema",
        icon: "tune-variant",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-control",
        accentColor: "#9C27B0",
        keywords: ["matching", "controllo", "control", "sistema", "toggle", "kill switch", "abilitazione", "disabilita", "abilita", "enable", "disable", "pausa matching", "reset matching"],
      },
      {
        key: "match-health",
        label: "Match Health",
        icon: "heart-pulse",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/match-health",
        accentColor: "#4CAF50",
        keywords: ["matching", "health", "salute", "stato", "status", "diagnostica", "disponibilità", "availability", "errore matching", "latenza matching", "anomalia"],
      },
      {
        key: "matching-telemetry",
        label: "Telemetria",
        icon: "chart-line",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/matching-telemetry",
        accentColor: "#22C55E",
        keywords: ["matching", "telemetria", "telemetry", "metriche", "dati", "statistiche", "log matching", "andamento", "trend", "grafico", "chart", "tempo reale"],
      },
      {
        key: "ab",
        label: "A/B Esperimenti",
        icon: "flask-outline",
        iconSet: "MaterialCommunityIcons",
        route: "/admin/ab",
        accentColor: "#E91E63",
        keywords: ["ab test", "esperimento", "experiment", "split test", "variante", "variant", "test", "gruppo controllo", "control group", "risultati test", "significatività", "conversion test"],
      },
    ],
  },
];
