// overflow di app/admin/ai-route-providers.tsx — StyleSheet estratto
import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  envBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: Colors.warning + "18",
    borderColor: Colors.warning + "55",
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  envBannerText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.warning,
    flex: 1,
    lineHeight: 18,
  },
  envBannerCode: { fontFamily: "Inter_600SemiBold" },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    marginBottom: 16,
  },
  cardTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: Colors.textSecondary,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  chainPreview: {
    fontFamily: "Inter_700Bold",
    fontSize: 16,
    color: Colors.text,
    marginBottom: 8,
  },
  hint: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 18,
  },
  sectionLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: Colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  providerCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    marginBottom: 12,
  },
  providerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  providerInfo: { flex: 1 },
  providerTitleRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 3 },
  providerLabel: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.text },
  posBadge: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  posBadgeText: { fontFamily: "Inter_700Bold", fontSize: 10, color: "#fff" },
  statusRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  statusText: { fontFamily: "Inter_400Regular", fontSize: 12 },
  toggleBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  toggleBtnOff: {
    backgroundColor: Colors.border,
  },
  providerDesc: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 17,
    marginBottom: 8,
  },
  testRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  testBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: Colors.background,
  },
  testBtnText: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
  },
  pingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexShrink: 1,
  },
  pingBadgeOk: { backgroundColor: Colors.success + "18" },
  pingBadgeErr: { backgroundColor: Colors.error + "18" },
  pingBadgeText: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
    flexShrink: 1,
  },
  reorderRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: 8,
  },
  reorderBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  reorderBtnDisabled: { opacity: 0.4 },
  reorderBtnText: { fontFamily: "Inter_500Medium", fontSize: 12, color: Colors.text },
  reorderBtnTextDisabled: { color: Colors.textSecondary },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.accent,
    borderRadius: 12,
    paddingVertical: 13,
    marginTop: 4,
    marginBottom: 16,
  },
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 15, color: "#fff" },
  infoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: Colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 12,
  },
  infoText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.textSecondary,
    flex: 1,
    lineHeight: 18,
  },
  code: { fontFamily: "Inter_600SemiBold", color: Colors.text },
  statRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 6,
    marginTop: 8,
  },
  statLabel: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    width: 56,
    textTransform: "capitalize" as const,
  },
  statBarWrap: {
    flex: 1,
    height: 6,
    backgroundColor: Colors.border,
    borderRadius: 3,
    overflow: "hidden" as const,
  },
  statBar: {
    height: 6,
    borderRadius: 3,
  },
  statCount: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: Colors.text,
    width: 34,
    textAlign: "right" as const,
  },
  statPct: {
    fontFamily: "Inter_400Regular",
    fontSize: 11,
    color: Colors.textSecondary,
    width: 34,
    textAlign: "right" as const,
  },
  testAllBtn: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.accent + "88",
    borderRadius: 12,
    paddingVertical: 11,
    paddingHorizontal: 16,
    marginBottom: 14,
    backgroundColor: Colors.accent + "10",
  },
  testAllBtnLoading: { opacity: 0.6 },
  testAllBtnText: {
    fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.accent,
  },
});
