import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surface,
    margin: 12,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  searchIcon: { marginRight: 8 },
  searchInput: {
    flex: 1,
    color: Colors.text,
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    padding: 0,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  totalCount: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: Colors.textSecondary,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.warning,
    backgroundColor: "transparent",
  },
  filterChipActive: {
    backgroundColor: Colors.warning,
    borderColor: Colors.warning,
  },
  filterChipText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: Colors.warning,
  },
  filterChipTextActive: {
    color: "#fff",
  },
  zeroMatchBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.warning,
    backgroundColor: "transparent",
  },
  zeroMatchBadgeActive: {
    backgroundColor: Colors.warning,
    borderColor: Colors.warning,
  },
  zeroMatchBadgeText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: Colors.warning,
  },
  zeroMatchBadgeTextActive: {
    color: "#fff",
  },
  refreshBtn: { padding: 4 },
  userRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.background,
    gap: 12,
  },
  avatarWrap: { position: "relative", width: 44, height: 44 },
  avatar: { width: 44, height: 44, borderRadius: 22 },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarLetter: { fontFamily: "Inter_700Bold", fontSize: 18 },
  typeBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: Colors.background,
  },
  typeBadgeText: { fontFamily: "Inter_700Bold", fontSize: 8, color: "#fff" },
  noMatchDot: {
    position: "absolute",
    top: -2,
    left: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.warning,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: Colors.background,
  },
  userInfo: { flex: 1, gap: 4 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  nickname: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    color: Colors.text,
    flexShrink: 1,
  },
  roleTag: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
    textTransform: "lowercase",
  },
  countChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
  },
  bzChipsRow: {
    borderTopWidth: 1,
    borderTopColor: "#E91E8C22",
    paddingTop: 3,
    marginTop: 1,
  },
  countChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 5,
    borderWidth: 1,
  },
  countChipLabel: {
    fontFamily: "Inter_500Medium",
    fontSize: 9,
  },
  countChipNum: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
  },
  noMatchText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.textSecondary,
    fontStyle: "italic",
  },
  totalBadge: { alignItems: "center", minWidth: 36 },
  totalText: { fontFamily: "Inter_700Bold", fontSize: 18, color: Colors.accent },
  totalLabel: { fontFamily: "Inter_400Regular", fontSize: 10, color: Colors.textSecondary },
  gapsBadge: { alignItems: "center", justifyContent: "center", width: 24 },
  gapsCount: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.error ?? "#F44336",
    alignItems: "center",
    justifyContent: "center",
  },
  gapsCountText: { fontFamily: "Inter_700Bold", fontSize: 11, color: "#fff" },
  separator: { height: 1, backgroundColor: Colors.border, marginLeft: 72 },
  empty: { alignItems: "center", paddingTop: 60, gap: 12 },
  emptyText: { fontFamily: "Inter_400Regular", fontSize: 15, color: Colors.textSecondary },
  loadMore: {
    margin: 16,
    padding: 12,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.border,
  },
  loadMoreText: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.accent },
});
