import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cardHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  cardTitle: { fontFamily: "Inter_700Bold", fontSize: 15, color: Colors.text },
  headerRight: { marginLeft: "auto", flexDirection: "row", alignItems: "center", gap: 8 },
  headerCount: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: Colors.textSecondary },
  healthDot: { width: 10, height: 10, borderRadius: 5 },
  list: { marginTop: 14, gap: 10 },
  errorText: { fontFamily: "Inter_400Regular", fontSize: 14, color: "#ef4444" },
  note: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    backgroundColor: Colors.background,
    borderRadius: 8,
    padding: 10,
    marginTop: 4,
  },
  noteBody: { flex: 1, gap: 4 },
  noteText: { fontFamily: "Inter_400Regular", fontSize: 13, color: Colors.textSecondary, lineHeight: 16 },
  legend: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
  legendText: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  mono: { fontFamily: "Inter_400Regular", fontSize: 12, color: "#9ca3af" },
  retryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: "rgba(96, 165, 250, 0.1)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(96, 165, 250, 0.25)",
    marginTop: 2,
  },
  retryButtonBusy: { opacity: 0.55 },
  retryText: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: "#60a5fa" },
  pushToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 10,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  pushToggleLeft: { flex: 1, gap: 2, flexDirection: "column" },
  pushToggleLabel: { fontFamily: "Inter_500Medium", fontSize: 13, color: Colors.text },
  pushToggleSub: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  maintenanceLabelActive: { color: "#f97316" },
  poweredOffLabelActive: { color: "#ef4444" },
  poweredOffOverlay: {
    alignItems: "center",
    paddingVertical: 22,
    paddingHorizontal: 12,
    gap: 8,
    marginTop: 10,
  },
  poweredOffOverlayTitle: { fontFamily: "Inter_700Bold", fontSize: 15, color: "#ef4444" },
  poweredOffOverlaySub: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: "center",
    lineHeight: 18,
  },
  poweredOffBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.35)",
  },
  poweredOffBadgeText: { fontFamily: "Inter_700Bold", fontSize: 10, color: "#ef4444", letterSpacing: 0.5 },
  ufwBadge: { justifyContent: "center", alignItems: "center" },
  maintenanceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: "rgba(249, 115, 22, 0.12)",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(249, 115, 22, 0.35)",
  },
  maintenanceBadgeText: { fontFamily: "Inter_700Bold", fontSize: 10, color: "#f97316", letterSpacing: 0.5 },
});
