import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  block: {
    marginTop: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    backgroundColor: "rgba(148, 163, 184, 0.04)",
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  headerIcon: { marginRight: 2 },
  headerText: { flex: 1 },
  title: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.text },
  subtitle: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary, marginTop: 1 },
  count: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.textSecondary, letterSpacing: 0.3 },
  dot: { width: 9, height: 9, borderRadius: 5 },
  body: {
    paddingHorizontal: 12,
    paddingBottom: 10,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(148, 163, 184, 0.12)",
    paddingTop: 8,
  },
  statusRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  statusLabel: { fontFamily: "Inter_400Regular", fontSize: 13, color: Colors.textSecondary },
  statusLabelError: { color: "#ef4444" },
  subtitleError: { color: "#ef4444" },
  meta: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  profilesRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 4 },
  profileChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: "rgba(167, 139, 250, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(167, 139, 250, 0.3)",
  },
  profileChipText: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: "#a78bfa" },
  metaRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 4 },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: "rgba(96, 165, 250, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(96, 165, 250, 0.2)",
  },
  metaChipError: {
    backgroundColor: "rgba(239, 68, 68, 0.08)",
    borderColor: "rgba(239, 68, 68, 0.25)",
  },
  metaText: { fontFamily: "Inter_500Medium", fontSize: 12, color: "#60a5fa" },
  publicNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 5,
    marginTop: 6,
    padding: 8,
    backgroundColor: "rgba(245, 158, 11, 0.06)",
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.2)",
  },
  publicNoteText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: "#f59e0b",
    flex: 1,
    lineHeight: 14,
  },
  fingerprintRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
  fingerprint: { fontFamily: "Inter_400Regular", fontSize: 10, color: "#6b7280", letterSpacing: 0.2 },
  tokenOkIcon: { marginLeft: 1 },
});
