import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  probeLogContainer: { marginTop: 6 },
  probeLogToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    alignSelf: "flex-start",
    paddingVertical: 3,
    paddingHorizontal: 8,
    backgroundColor: "rgba(167, 139, 250, 0.08)",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(167, 139, 250, 0.2)",
  },
  probeLogIcon: { marginRight: 1 },
  probeLogToggleText: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: "#a78bfa" },
  probeLogList: {
    marginTop: 6,
    gap: 4,
    paddingLeft: 4,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(167, 139, 250, 0.2)",
  },
  probeLogRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingLeft: 6,
    paddingVertical: 1,
  },
  probeLogTimestamp: {
    fontFamily: "Inter_400Regular",
    fontSize: 10,
    color: "#6b7280",
    letterSpacing: 0.2,
    minWidth: 72,
  },
  probeLogDot: { width: 6, height: 6, borderRadius: 3, flexShrink: 0 },
  probeLogLatency: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: "#9ca3af",
    minWidth: 40,
  },
  probeLogDetail: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: "#9ca3af",
    flex: 1,
    lineHeight: 13,
  },
  historyContainer: { marginTop: 6 },
  historyToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    alignSelf: "flex-start",
    paddingVertical: 3,
    paddingHorizontal: 8,
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.2)",
  },
  historyIcon: { marginRight: 1 },
  historyToggleText: { fontFamily: "Inter_600SemiBold", fontSize: 12, color: "#f59e0b" },
  historyList: {
    marginTop: 6,
    gap: 5,
    paddingLeft: 4,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(245, 158, 11, 0.25)",
  },
  historyItem: { gap: 1, paddingLeft: 6 },
  historyTimestamp: { fontFamily: "Inter_600SemiBold", fontSize: 10, color: "#6b7280", letterSpacing: 0.3 },
  historyError: { fontFamily: "Inter_400Regular", fontSize: 12, color: "#9ca3af", lineHeight: 14 },
  eventLogContainer: { marginTop: 4 },
  eventLogToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    alignSelf: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 10,
    backgroundColor: "rgba(96, 165, 250, 0.08)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(96, 165, 250, 0.2)",
  },
  eventLogIcon: { marginRight: 1 },
  eventLogToggleText: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: "#60a5fa" },
  filterRow: { marginTop: 8 },
  filterRowContent: { gap: 6, paddingHorizontal: 4 },
  filterChip: {
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
    backgroundColor: "rgba(148, 163, 184, 0.07)",
  },
  filterChipActive: {
    borderColor: "rgba(96, 165, 250, 0.5)",
    backgroundColor: "rgba(96, 165, 250, 0.12)",
  },
  filterChipText: { fontFamily: "Inter_500Medium", fontSize: 12, color: Colors.textSecondary },
  filterChipTextActive: { color: "#60a5fa" },
  eventList: {
    marginTop: 8,
    gap: 4,
    paddingLeft: 4,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(96, 165, 250, 0.2)",
  },
  eventEmpty: { fontFamily: "Inter_400Regular", fontSize: 12, color: "#6b7280", paddingLeft: 8, paddingVertical: 4 },
  eventRow: { flexDirection: "row", alignItems: "center", gap: 6, paddingLeft: 6, paddingVertical: 2 },
  eventTime: { fontFamily: "Inter_400Regular", fontSize: 10, color: "#6b7280", letterSpacing: 0.2, minWidth: 64 },
  eventTransition: { flexDirection: "row", alignItems: "center", gap: 3, flex: 1 },
  eventDot: { width: 6, height: 6, borderRadius: 3 },
  eventState: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  eventService: { fontFamily: "Inter_400Regular", fontSize: 10, color: "#9ca3af", letterSpacing: 0.2 },
  ghBlock: {
    marginTop: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    backgroundColor: "rgba(148, 163, 184, 0.04)",
    overflow: "hidden",
  },
  ghHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  ghHeaderIcon: { marginRight: 2 },
  ghHeaderText: { flex: 1 },
  ghTitle: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.text },
  ghSubtitle: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary, marginTop: 1 },
  ghCount: { fontFamily: "Inter_600SemiBold", fontSize: 13, color: Colors.textSecondary, letterSpacing: 0.3 },
  ghDot: { width: 9, height: 9, borderRadius: 5 },
  ghList: {
    paddingHorizontal: 12,
    paddingBottom: 10,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(148, 163, 184, 0.12)",
    paddingTop: 8,
  },
  ghRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  ghRowText: { flex: 1, gap: 2 },
  ghRowTop: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap" },
  ghAreaName: { fontFamily: "Inter_500Medium", fontSize: 12, color: Colors.text },
  ghAreaStatus: { fontFamily: "Inter_400Regular", fontSize: 12, color: Colors.textSecondary },
  tierBadge: { paddingHorizontal: 6, paddingVertical: 1, borderRadius: 5, borderWidth: 1 },
  tierBadgeCore: { backgroundColor: "rgba(59, 130, 246, 0.12)", borderColor: "rgba(59, 130, 246, 0.35)" },
  tierBadgeOnDemand: { backgroundColor: "rgba(148, 163, 184, 0.1)", borderColor: "rgba(148, 163, 184, 0.3)" },
  tierBadgeText: { fontFamily: "Inter_600SemiBold", fontSize: 8, letterSpacing: 0.4 },
  tierBadgeTextCore: { color: "#60a5fa" },
  tierBadgeTextOnDemand: { color: "#9ca3af" },
  disabledBadge: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 5,
    backgroundColor: "rgba(107, 114, 128, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(107, 114, 128, 0.3)",
  },
  disabledBadgeText: { fontFamily: "Inter_600SemiBold", fontSize: 8, color: "#9ca3af", letterSpacing: 0.3 },
  ghFingerprintRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
  ghFingerprint: { fontFamily: "Inter_400Regular", fontSize: 10, color: "#6b7280", letterSpacing: 0.2 },
  tokenOkIcon: { marginLeft: 1 },
});
