import React from "react";
import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const traduzioniStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: 16,
    gap: 14,
  },
  pageDesc: {
    fontSize: 13,
    color: Colors.textSecondary,
    fontFamily: "Inter_400Regular",
    marginBottom: 4,
  },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  cardHeaderText: { flex: 1 },
  stepBadge: {
    width: 30, height: 30, borderRadius: 15,
    backgroundColor: Colors.accent,
    alignItems: "center", justifyContent: "center",
  },
  stepBadgeSuccess: { backgroundColor: "#4CAF50" },
  stepBadgeError: { backgroundColor: "#F44336" },
  stepBadgeText: { color: "#fff", fontSize: 14, fontFamily: "Inter_700Bold" },
  cardTitle: { fontSize: 15, color: Colors.text, fontFamily: "Inter_600SemiBold", marginBottom: 2 },
  cardDesc: { fontSize: 12, color: Colors.textSecondary, fontFamily: "Inter_400Regular", lineHeight: 16 },
  button: {
    backgroundColor: Colors.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8,
  },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: "#fff", fontSize: 14, fontFamily: "Inter_600SemiBold" },
  buttonSecondary: {
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: Colors.accent,
  },
  buttonSecondaryText: { color: Colors.accent, fontSize: 14, fontFamily: "Inter_600SemiBold" },
  secondaryButton: {
    backgroundColor: "transparent",
    borderRadius: 10,
    paddingVertical: 12,
    borderWidth: 1.5,
    borderColor: Colors.accent,
    alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8,
  },
  secondaryButtonText: { color: Colors.accent, fontSize: 14, fontFamily: "Inter_600SemiBold" },
  resultBox: {
    marginTop: 10, paddingHorizontal: 10, paddingVertical: 8,
    borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 6,
    backgroundColor: Colors.background,
  },
  resultBoxSuccess: { backgroundColor: "#4CAF5015" },
  resultBoxError: { backgroundColor: "#F4433615" },
  resultText: { fontSize: 12, fontFamily: "Inter_400Regular", flex: 1 },
  resultTextSuccess: { color: "#4CAF50" },
  resultTextError: { color: "#F44336" },
  langPicker: { marginBottom: 12 },
  langPickerLabel: {
    fontSize: 12, color: Colors.textSecondary,
    fontFamily: "Inter_500Medium", marginBottom: 8,
  },
  checkbox: {
    flexDirection: "row", alignItems: "center", gap: 8,
    paddingVertical: 6,
  },
  checkboxLabel: { fontSize: 13, color: Colors.text, fontFamily: "Inter_400Regular" },
  sectionDivider: { height: 1, backgroundColor: Colors.border, marginVertical: 10 },
  inlineHint: {
    marginTop: 8, paddingHorizontal: 8, paddingVertical: 6,
    borderRadius: 6, flexDirection: "row", alignItems: "center", gap: 6,
  },
  inlineHintOk: { backgroundColor: "#4CAF5015" },
  inlineHintErr: { backgroundColor: "#eb575715" },
  inlineHintText: { fontSize: 12, fontFamily: "Inter_400Regular", flex: 1 },
  importFileName: {
    marginTop: 8,
    fontSize: 12,
    color: Colors.textSecondary,
    fontFamily: "Inter_500Medium",
  },
  infoBanner: {
    flexDirection: "row", gap: 12,
    backgroundColor: Colors.accent + "15",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.accent + "30",
  },
  infoBannerText: { flex: 1 },
  infoBannerTitle: { fontSize: 13, color: Colors.text, fontFamily: "Inter_600SemiBold", marginBottom: 4 },
  infoBannerBody: { fontSize: 12, color: Colors.textSecondary, fontFamily: "Inter_400Regular", lineHeight: 18 },
  langChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  langChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.background,
  },
  langChipActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accent + "15",
  },
  langChipFixed: {
    borderColor: Colors.textSecondary,
    backgroundColor: Colors.surface,
    opacity: 0.7,
  },
  langChipText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
  },
  langChipTextActive: {
    color: Colors.accent,
  },
  langChipTextFixed: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 10,
    marginBottom: 8,
    marginTop: 4,
  },
  searchIcon: {
    marginRight: 6,
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: Colors.text,
  },
  searchClear: {
    padding: 4,
  },
  categoryChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  categoryChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.background,
  },
  categoryChipActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accent + "15",
  },
  categoryChipText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
  },
  categoryChipTextActive: {
    color: Colors.accent,
  },
  filterCount: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    marginBottom: 6,
  },
  tableContainer: {
    marginTop: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  tableHeaderRow: {
    backgroundColor: Colors.accent,
  },
  tableHeaderCell: {
    padding: 8,
    justifyContent: "center",
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.2)",
  },
  tableHeaderText: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  tableCell: {
    padding: 8,
    justifyContent: "center",
    borderRightWidth: 1,
    borderRightColor: Colors.border,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 4,
  },
  tableCellText: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: Colors.text,
    flex: 1,
  },
  tableCellEmpty: {
    color: Colors.textSecondary,
    fontStyle: "italic",
  },
  tableCellKey: {
    fontSize: 12,
    fontFamily: "Inter_500Medium",
    color: Colors.text,
    lineHeight: 16,
  },
  tableCellSubKey: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    marginTop: 2,
  },
  tableCellTappable: {
    backgroundColor: "transparent",
  },
  tableCellEditing: {
    backgroundColor: Colors.accent + "10",
    padding: 4,
  },
  tableCellInput: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: Colors.text,
    minHeight: 36,
    padding: 4,
    borderWidth: 1,
    borderColor: Colors.accent,
    borderRadius: 4,
    backgroundColor: Colors.background,
  },
  tableCellSaving: {
    backgroundColor: Colors.accent + "08",
  },
  tableCellOk: {
    backgroundColor: "#4CAF5010",
  },
  tableCellError: {
    backgroundColor: "#F4433610",
  },
  tableRowMissing: {
    borderLeftWidth: 3,
    borderLeftColor: "#FF9800",
    backgroundColor: "#FF980008",
  },
  missingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#FF9800",
    alignSelf: "center",
    flexShrink: 0,
    marginLeft: 4,
  },
  positionCellContent: {
    flex: 1,
    flexDirection: "column",
  },
  missingFilterRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  missingChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#FF9800",
    backgroundColor: "transparent",
  },
  missingChipActive: {
    backgroundColor: "#FF980020",
  },
  missingChipText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: "#FF9800",
  },
  missingChipTextActive: {
    color: "#FF9800",
  },
  missingDotSmall: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#FF9800",
  },
  aiSummaryBox: {
    marginTop: 10,
    backgroundColor: Colors.background,
    borderRadius: 8,
    padding: 10,
    gap: 6,
  },
  aiSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  aiSummaryLang: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.accent,
    width: 36,
  },
  aiSummaryCount: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    flex: 1,
    marginLeft: 8,
  },
});
