-- One-shot cleanup: delete all erroneous 'new' biker_zavorrina_matches
-- generated by the old matching-engine bug (separate if blocks instead of if/else if).
-- The bug caused matches on brand-only when wishlist specified brand+model,
-- producing ~2.27M incorrect records (710 MB).
-- Fix applied in Task #59 (matching-engine.ts if/else if chain).
-- This script was executed on 2026-03-17 and deleted 2,267,373 records.
-- Preserved: accepted (2) and rejected (48) records.
--
-- Run with: psql "$DATABASE_URL" -f scripts/cleanup-new-garage-matches.sql
-- After running, execute: VACUUM FULL biker_zavorrina_matches;

DO $$
DECLARE
  deleted_count INT;
  total_deleted INT := 0;
BEGIN
  LOOP
    DELETE FROM biker_zavorrina_matches
    WHERE id IN (
      SELECT id FROM biker_zavorrina_matches
      WHERE status = 'new'
      LIMIT 50000
    );
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    total_deleted := total_deleted + deleted_count;
    RAISE NOTICE 'Deleted batch: %, Total so far: %', deleted_count, total_deleted;
    EXIT WHEN deleted_count = 0;
  END LOOP;
  RAISE NOTICE 'Cleanup complete. Total deleted: %', total_deleted;
END;
$$;

-- Reclaim disk space (blocking operation, run during low-traffic window)
VACUUM FULL biker_zavorrina_matches;

-- Verify result
SELECT status, COUNT(*) FROM biker_zavorrina_matches GROUP BY status;
SELECT pg_size_pretty(pg_total_relation_size('biker_zavorrina_matches')) AS table_size;
