// LARGE-FILE-LOCKED — limite: 630 righe (attuali: 588)
// Aggiungi nuove funzionalità in: shared/db/matching-extra.ts
// Motivo: file delicato di dimensione media. Splittare ora introduce rischio.
//         Vedi Task #2584 (regola 600 righe) e Task "Lock dimensione file priorità media".

import { sql } from "drizzle-orm";
import {
  pgTable,
  varchar,
  text,
  integer,
  boolean,
  timestamp,
  doublePrecision,
  jsonb,
  index,
  uniqueIndex,
  foreignKey,
} from "drizzle-orm/pg-core";
import { z } from "zod";
import { users, userMotorcycles } from "./users";
import { plannedRoutes } from "./planned-routes";

export const zavorrinaWishlists = pgTable("zavorrina_wishlists", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 })
    .notNull()
    .unique()
    .references(() => users.id, { onDelete: "cascade" }),
  description: text("description"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const zavorrinaWishlistPhotos = pgTable("zavorrina_wishlist_photos", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  wishlistId: varchar("wishlist_id", { length: 36 })
    .notNull()
    .references(() => zavorrinaWishlists.id, { onDelete: "cascade" }),
  photoUrl: text("photo_url").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const zavorrinaWishlistMotos = pgTable("zavorrina_wishlist_motos", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  wishlistId: varchar("wishlist_id", { length: 36 })
    .notNull()
    .references(() => zavorrinaWishlists.id, { onDelete: "cascade" }),
  brand: varchar("brand", { length: 100 }),
  model: varchar("model", { length: 100 }),
  motorcycleType: varchar("motorcycle_type", { length: 50 }),
  ridingStyle: varchar("riding_style", { length: 50 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("wishlist_motos_wishlist_idx").on(table.wishlistId),
  index("wishlist_motos_brand_idx").on(table.brand),
  index("wishlist_motos_brand_model_idx").on(table.brand, table.model),
  index("wishlist_motos_type_idx").on(table.motorcycleType),
]);

export const bikerZavorrinaMatches = pgTable("biker_zavorrina_matches", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  bikerId: varchar("biker_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  zavorrinaId: varchar("zavorrina_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  // Task #2680 — FK names auto-generated by Drizzle exceed 63 chars, PG silently
  // truncates them. Using explicit names that match what PostgreSQL stores (63-char
  // truncated values) keeps FK semantics identical and avoids spurious schema diffs.
  bikerMotorcycleId: varchar("biker_motorcycle_id", { length: 36 }).notNull(),
  wishlistMotoId: varchar("wishlist_moto_id", { length: 36 }).notNull(),
  status: varchar("status", { length: 20 }).notNull().default("new"),
  isSupermatch: boolean("is_supermatch").notNull().default(false),
  scoreBreakdown: jsonb("score_breakdown").notNull().default(sql`'{}'::jsonb`),
  notificationPriority: varchar("notification_priority", { length: 10 }).notNull().default("normal"),
  notifiedAt: timestamp("notified_at"),
  archivedAt: timestamp("archived_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("matches_biker_id_idx").on(table.bikerId),
  index("matches_zavorrina_id_idx").on(table.zavorrinaId),
  index("matches_bz_notif_pending_idx").on(table.notificationPriority, table.notifiedAt),
  uniqueIndex("matches_unique_combo_idx").on(table.bikerId, table.zavorrinaId, table.bikerMotorcycleId, table.wishlistMotoId),
  index("bz_matches_archived_at_idx").on(table.archivedAt),
  // Explicit FK names = exact 63-char PG-truncated versions of the auto-generated names.
  foreignKey({
    name: "biker_zavorrina_matches_biker_motorcycle_id_user_motorcycles_id",
    columns: [table.bikerMotorcycleId],
    foreignColumns: [userMotorcycles.id],
  }).onDelete("cascade"),
  foreignKey({
    name: "biker_zavorrina_matches_wishlist_moto_id_zavorrina_wishlist_mot",
    columns: [table.wishlistMotoId],
    foreignColumns: [zavorrinaWishlistMotos.id],
  }).onDelete("cascade"),
]);

// bikerBikerMatches — definita in shared/db/matching-drizzle-excluded.ts.
// NOTA: nessun re-export qui. Il consumer usa `@shared/db` (shared/db/index.ts
// ri-esporta entrambi i file matching come unico punto di accesso).
// La tabella è esclusa da drizzle-kit (tablesFilter in drizzle.config.ts);
// le sue migration passano da numbered SQL in migrations/.

export const directMatchRequests = pgTable("direct_match_requests", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  senderId: varchar("sender_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  receiverId: varchar("receiver_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  status: varchar("status", { length: 20 }).notNull().default("pending"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  uniqueIndex("direct_match_requests_unique_idx").on(table.senderId, table.receiverId),
  index("direct_match_requests_receiver_idx").on(table.receiverId),
  index("direct_match_requests_sender_idx").on(table.senderId),
]);

export const matchPreferences = pgTable("match_preferences", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 })
    .notNull()
    .unique()
    .references(() => users.id, { onDelete: "cascade" }),
  bikerBikerBrand: boolean("biker_biker_brand").notNull().default(true),
  bikerZavorrinaBrand: boolean("biker_zavorrina_brand").notNull().default(true),
  bikerClubBrand: boolean("biker_club_brand").notNull().default(true),
  zavorrinaClubBrand: boolean("zavorrina_club_brand").notNull().default(true),
  bikerBikerTypeStyle: boolean("biker_biker_type_style").notNull().default(true),
  bikerZavorrinaTypeStyle: boolean("biker_zavorrina_type_style").notNull().default(true),
  bikerBikerDistance: boolean("biker_biker_distance").notNull().default(true),
  bikerZavorrinaDistance: boolean("biker_zavorrina_distance").notNull().default(true),
  bikerBikerMusic: boolean("biker_biker_music").notNull().default(true),
  bikerZavorrinaMusic: boolean("biker_zavorrina_music").notNull().default(true),
  bikerBikerLeanAngle: boolean("biker_biker_lean_angle").notNull().default(true),
  bikerBikerRouteTypeZone: boolean("biker_biker_route_type_zone").notNull().default(true),
  bikerZavorrinaRouteTypeZone: boolean("biker_zavorrina_route_type_zone").notNull().default(true),
  bikerBikerAvgSpeed: boolean("biker_biker_avg_speed").notNull().default(true),
  bikerBikerAvgDuration: boolean("biker_biker_avg_duration").notNull().default(true),
  bikerBikerDayTime: boolean("biker_biker_day_time").notNull().default(true),
  bikerBikerEvents: boolean("biker_biker_events").notNull().default(true),
  routeAffinity: boolean("route_affinity").notNull().default(true),
  // Task #2516 — abilita matcher per affinità musicale combinata
  // (tag-overlap + embedding similarity sui gusti musicali liberi).
  musicAffinity: boolean("music_affinity").notNull().default(true),
  bioAffinity: boolean("bio_affinity").notNull().default(true),
  // Task #3393 — toggle dedicato per il matcher telemetry-affinity (stile di
  // guida da ride_telemetry). Ortogonale a bikerBikerLeanAngle/AvgSpeed/AvgDuration.
  telemetryAffinity: boolean("telemetry_affinity").notNull().default(true),
  // Task #2580 — allinea match_preferences al registry (timeOverlap #2521).
  timeOverlap: boolean("time_overlap").notNull().default(true),
  // Task #2528 — preferenza per ricevere inviti su giri pianificati compatibili.
  plannedRouteInvite: boolean("planned_route_invite").notNull().default(true),
  directMatch: boolean("direct_match").notNull().default(true),
  topMatchesOnly: boolean("top_matches_only").notNull().default(false),
  weeklyRecap: boolean("weekly_recap").notNull().default(true),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  index("match_preferences_user_id_idx").on(table.userId),
]);

export const weeklyRecaps = pgTable("weekly_recaps", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  weekStart: timestamp("week_start").notNull(),
  topMatches: jsonb("top_matches").notNull().default(sql`'[]'::jsonb`),
  stats: jsonb("stats").notNull().default(sql`'{}'::jsonb`),
  pushSentAt: timestamp("push_sent_at"),
  openedAt: timestamp("opened_at"),
  matchClickedAt: timestamp("match_clicked_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("weekly_recaps_user_idx").on(table.userId, table.weekStart),
  uniqueIndex("weekly_recaps_user_week_idx").on(table.userId, table.weekStart),
]);

export type WeeklyRecap = typeof weeklyRecaps.$inferSelect;
export type InsertWeeklyRecap = typeof weeklyRecaps.$inferInsert;

/**
 * Task #2516 — Match per affinità musicale combinata.
 *
 * Combina tag-overlap (Jaccard sui tag della categoria "musica") con la
 * similarità coseno dell'embedding `music_taste` (testo libero + tag).
 * Score finale: tagScore * w1 + embeddingScore * w2 (default 0.5/0.5).
 */
export const musicAffinityMatches = pgTable("music_affinity_matches", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userAId: varchar("user_a_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  userBId: varchar("user_b_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  tagScore: doublePrecision("tag_score").notNull().default(0),
  embeddingScore: doublePrecision("embedding_score").notNull().default(0),
  combinedScore: doublePrecision("combined_score").notNull(),
  tagCommon: integer("tag_common").notNull().default(0),
  status: varchar("status", { length: 20 }).notNull().default("new"),
  notificationPriority: varchar("notification_priority", { length: 10 }).notNull().default("normal"),
  notifiedAt: timestamp("notified_at"),
  archivedAt: timestamp("archived_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("music_affinity_user_a_idx").on(table.userAId),
  index("music_affinity_user_b_idx").on(table.userBId),
  index("music_affinity_archived_at_idx").on(table.archivedAt),
  uniqueIndex("music_affinity_symmetric_idx").on(
    sql`LEAST(${table.userAId}, ${table.userBId})`,
    sql`GREATEST(${table.userAId}, ${table.userBId})`,
  ),
]);

export type MusicAffinityMatch = typeof musicAffinityMatches.$inferSelect;
export type InsertMusicAffinityMatch = typeof musicAffinityMatches.$inferInsert;

export const userRouteFingerprints = pgTable("user_route_fingerprints", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 })
    .notNull()
    .unique()
    .references(() => users.id, { onDelete: "cascade" }),
  cells: jsonb("cells").notNull().default(sql`'{}'::jsonb`),
  cellCount: integer("cell_count").notNull().default(0),
  centerLat: doublePrecision("center_lat"),
  centerLon: doublePrecision("center_lon"),
  lastRouteAt: timestamp("last_route_at"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  index("user_route_fingerprints_user_id_idx").on(table.userId),
  index("user_route_fingerprints_cell_count_idx").on(table.cellCount),
]);

export const geoCellLabels = pgTable("geo_cell_labels", {
  geohash: varchar("geohash", { length: 12 }).primaryKey(),
  label: varchar("label", { length: 200 }).notNull(),
  centerLat: doublePrecision("center_lat"),
  centerLon: doublePrecision("center_lon"),
  visitCount: integer("visit_count").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const routeAffinityMatches = pgTable("route_affinity_matches", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userAId: varchar("user_a_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  userBId: varchar("user_b_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  commonCells: integer("common_cells").notNull(),
  score: doublePrecision("score").notNull(),
  topPlaces: jsonb("top_places").notNull().default(sql`'[]'::jsonb`),
  status: varchar("status", { length: 20 }).notNull().default("new"),
  notificationPriority: varchar("notification_priority", { length: 10 }).notNull().default("normal"),
  notifiedAt: timestamp("notified_at"),
  archivedAt: timestamp("archived_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("route_affinity_user_a_idx").on(table.userAId),
  index("route_affinity_user_b_idx").on(table.userBId),
  index("route_affinity_notif_pending_idx").on(table.notificationPriority, table.notifiedAt),
  index("route_affinity_archived_at_idx").on(table.archivedAt),
  uniqueIndex("route_affinity_symmetric_idx").on(
    sql`LEAST(${table.userAId}, ${table.userBId})`,
    sql`GREATEST(${table.userAId}, ${table.userBId})`,
  ),
]);

export type UserRouteFingerprint = typeof userRouteFingerprints.$inferSelect;
export type InsertUserRouteFingerprint = typeof userRouteFingerprints.$inferInsert;
export type GeoCellLabel = typeof geoCellLabels.$inferSelect;
export type InsertGeoCellLabel = typeof geoCellLabels.$inferInsert;
export type RouteAffinityMatch = typeof routeAffinityMatches.$inferSelect;
export type InsertRouteAffinityMatch = typeof routeAffinityMatches.$inferInsert;

/**
 * Task #2528 — Curvy profile aggregato per utente.
 * Media dei curvy-score delle rotte percorse, alimenta `curvy_affinity` in scoring.
 */
export const userCurvyProfile = pgTable("user_curvy_profile", {
  userId: varchar("user_id", { length: 36 })
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  avgCurvy: doublePrecision("avg_curvy").notNull().default(0),
  sampleCount: integer("sample_count").notNull().default(0),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  index("user_curvy_profile_avg_idx").on(table.avgCurvy),
]);

export type UserCurvyProfile = typeof userCurvyProfile.$inferSelect;
export type InsertUserCurvyProfile = typeof userCurvyProfile.$inferInsert;

/**
 * Task #3393 — Telemetry Affinity matches.
 *
 * Match per coppia di utenti basato sullo stile di guida aggregato in
 * `user_telemetry_profile`. Score combinato:
 *   combinedScore = 0.4 * algorithmicScore (Jaccard sui 3 bucket) +
 *                   0.6 * embeddingScore (coseno pgvector su `telemetry_style`).
 * `styleLabels` contiene le label comuni (es. ["sport_rider", "evening_rider"]).
 */
export const telemetryAffinityMatches = pgTable("telemetry_affinity_matches", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userAId: varchar("user_a_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  userBId: varchar("user_b_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  algorithmicScore: doublePrecision("algorithmic_score").notNull().default(0),
  embeddingScore: doublePrecision("embedding_score").notNull().default(0),
  combinedScore: doublePrecision("combined_score").notNull(),
  styleLabels: jsonb("style_labels").notNull().default(sql`'[]'::jsonb`),
  status: varchar("status", { length: 20 }).notNull().default("new"),
  notificationPriority: varchar("notification_priority", { length: 10 }).notNull().default("normal"),
  notifiedAt: timestamp("notified_at"),
  archivedAt: timestamp("archived_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("telemetry_affinity_user_a_idx").on(table.userAId),
  index("telemetry_affinity_user_b_idx").on(table.userBId),
  index("telemetry_affinity_combined_score_idx").on(table.combinedScore),
  index("telemetry_affinity_archived_at_idx").on(table.archivedAt),
  uniqueIndex("telemetry_affinity_symmetric_idx").on(
    sql`LEAST(${table.userAId}, ${table.userBId})`,
    sql`GREATEST(${table.userAId}, ${table.userBId})`,
  ),
]);

export type TelemetryAffinityMatch = typeof telemetryAffinityMatches.$inferSelect;
export type InsertTelemetryAffinityMatch = typeof telemetryAffinityMatches.$inferInsert;

/**
 * Task #2528 — Inviti a giri pianificati suggeriti dal matcher
 * `run-planned-route-affinity.ts`. Unique su (route_id, suggested_user_id).
 */
export const plannedRouteInvites = pgTable("planned_route_invites", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  routeId: varchar("route_id", { length: 36 }).notNull(),
  ownerId: varchar("owner_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  suggestedUserId: varchar("suggested_user_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  score: doublePrecision("score").notNull(),
  reasons: jsonb("reasons").notNull().default(sql`'{}'::jsonb`),
  priority: varchar("priority", { length: 10 }).notNull().default("normal"),
  status: varchar("status", { length: 20 }).notNull().default("suggested"),
  notifiedAt: timestamp("notified_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("planned_route_invites_route_idx").on(table.routeId),
  index("planned_route_invites_suggested_idx").on(table.suggestedUserId),
  uniqueIndex("planned_route_invites_unique_idx").on(table.routeId, table.suggestedUserId),
  foreignKey({
    name: "planned_route_invites_route_id_fk",
    columns: [table.routeId],
    foreignColumns: [plannedRoutes.id],
  }).onDelete("cascade"),
]);

export type PlannedRouteInvite = typeof plannedRouteInvites.$inferSelect;
export type InsertPlannedRouteInvite = typeof plannedRouteInvites.$inferInsert;

/**
 * Task #2515 — Bio affinity matches (cosine similarity on user bio embeddings).
 * userA/userB are stored sorted via the LEAST/GREATEST unique index.
 */
export const bioAffinityMatches = pgTable("bio_affinity_matches", {
  id: varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userAId: varchar("user_a_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  userBId: varchar("user_b_id", { length: 36 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  similarity: doublePrecision("similarity").notNull(),
  model: varchar("model", { length: 80 }),
  status: varchar("status", { length: 20 }).notNull().default("new"),
  notificationPriority: varchar("notification_priority", { length: 10 }).notNull().default("normal"),
  notifiedAt: timestamp("notified_at"),
  archivedAt: timestamp("archived_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => [
  index("bio_affinity_user_a_idx").on(table.userAId),
  index("bio_affinity_user_b_idx").on(table.userBId),
  index("bio_affinity_notif_pending_idx").on(table.notificationPriority, table.notifiedAt),
  uniqueIndex("bio_affinity_symmetric_idx").on(
    sql`LEAST(${table.userAId}, ${table.userBId})`,
    sql`GREATEST(${table.userAId}, ${table.userBId})`,
  ),
]);

export type BioAffinityMatch = typeof bioAffinityMatches.$inferSelect;
export type InsertBioAffinityMatch = typeof bioAffinityMatches.$inferInsert;

export type ZavorrinaWishlist = typeof zavorrinaWishlists.$inferSelect;
export type InsertZavorrinaWishlist = typeof zavorrinaWishlists.$inferInsert;
export type ZavorrinaWishlistPhoto = typeof zavorrinaWishlistPhotos.$inferSelect;
export type InsertZavorrinaWishlistPhoto = typeof zavorrinaWishlistPhotos.$inferInsert;
export type ZavorrinaWishlistMoto = typeof zavorrinaWishlistMotos.$inferSelect;
export type InsertZavorrinaWishlistMoto = typeof zavorrinaWishlistMotos.$inferInsert;
export type BikerZavorrinaMatch = typeof bikerZavorrinaMatches.$inferSelect;
export type InsertBikerZavorrinaMatch = typeof bikerZavorrinaMatches.$inferInsert;
// BikerBikerMatch / InsertBikerBikerMatch — definiti in shared/db/matching-drizzle-excluded.ts, accessibili via `@shared/db`.
export type DirectMatchRequest = typeof directMatchRequests.$inferSelect;
export type InsertDirectMatchRequest = typeof directMatchRequests.$inferInsert;

export type MatchPreferences = typeof matchPreferences.$inferSelect;
export type InsertMatchPreferences = typeof matchPreferences.$inferInsert;

export * from "./matching.part2";

export const matchPreferencesAdminUpdateSchema = z.record(z.string(), z.boolean()).and(z.object({}).passthrough());
